"""Regenerate luauvmp/signatures.py from labelled samples.

Usage:  python tools/gen_signatures.py <sample.lua> [<sample2.lua> ...]

Each sample needs an entry in LABELS below, mapping opcode number -> canonical
name.  Labels come from reading the canonical handler dumps produced by
`luauvmp inspect --handlers`; only label a handler you can actually read.
Signatures are build-independent, so one labelled build teaches the tool every
other build that reuses the same handler.
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from luauvmp.analyse import analyse  # noqa: E402

# --------------------------------------------------------------------- labels
LABELS = {
    # reference build
    'auto-bond': {
        3: 'JUMPIFNOTLE', 10: 'ORK', 11: 'MULK', 15: 'FORNPREP', 19: 'CLOSEUPVALS',
        27: 'LOADB', 28: 'FORNLOOP', 40: 'FORGLOOP', 45: 'JUMPXEQKB', 46: 'NEWCLOSURE',
        50: 'JUMPIFNOT', 51: 'JUMPIFEQ', 54: 'JUMPXEQKS', 55: 'CONCAT', 59: 'JUMP',
        61: 'GETTABLEN', 62: 'DIVK', 72: 'SETUPVAL', 82: 'GETTABLE', 87: 'GETTABLEKS',
        90: 'JUMPIF', 95: 'MODK', 104: 'NAMECALL', 107: 'JUMPIFLE', 112: 'JUMPXEQKS',
        113: 'GETVARARGS', 114: 'GETUPVAL', 120: 'RETURN', 130: 'SUB', 134: 'SETTABLE',
        135: 'NEWTABLE', 137: 'LOADK', 140: 'LOADNIL', 142: 'LOADNIL',
        148: 'NEWCLOSURE2', 166: 'ADD', 171: 'MOVE', 187: 'JUMPIFNOTEQ', 193: 'NOP',
        196: 'JUMPXEQKNIL', 197: 'DECIMPORT', 198: 'JUMPIFNOTLT', 208: 'ADDK',
        211: 'SETTABLEKS', 218: 'NOP', 221: 'CALL', 222: 'JUMP', 223: 'SETLIST',
        224: 'FORGPREP', 226: 'LOADN', 232: 'FORGPREP_F', 236: 'LEN',
        245: 'GETIMPORT', 248: 'SETTABLEN', 250: 'NOP', 253: 'DECSTR', 255: 'DECSTR',
    },
    # second build - only handlers whose canonical form is unambiguous
    'FN_AnimalHospital': {
        6: 'FORNPREP', 10: 'DIV', 12: 'GETIMPORT', 25: 'FORGLOOP', 28: 'MOVE',
        41: 'NEWCLOSURE2', 44: 'DECSTR', 63: 'JUMP', 90: 'CALL', 97: 'FORNLOOP',
        43: 'SETLIST', 47: 'ORK', 86: 'OR', 137: 'FORGPREP', 138: 'GETVARARGS',
        140: 'CALL', 186: 'GETUPVAL', 198: 'NEWTABLE', 211: 'RETURN',
        68: 'GETTABLEN', 148: 'CLOSEUPVALS', 209: 'SUBK',
        218: 'JUMPIFLT', 228: 'NEWCLOSURE', 238: 'DECIMPORT', 240: 'CONCAT',
    },
    # third build - MoonVeil v1.4.5, staged payload
    'script': {
        3: 'CLOSEUPVALS', 10: 'DECSTR', 27: 'MINUS', 52: 'CONCAT', 58: 'DECIMPORT',
        71: 'NEWCLOSURE', 91: 'GETIMPORT', 92: 'CALL', 96: 'NEWCLOSURE2',
        106: 'GETVARARGS', 115: 'LOADNIL', 147: 'MUL', 152: 'FORNPREP',
        171: 'POW', 178: 'MOVE', 192: 'RETURN', 228: 'JUMP',
    },
}


def main():
    sigs, fields, conflicts = {}, {}, []
    # first operand order seen for each canonical name, per arity
    by_name = {}
    for path in sys.argv[1:]:
        stem = os.path.splitext(os.path.basename(path))[0]
        labels = LABELS.get(stem)
        if labels is None:
            print('no labels for %s - skipping' % stem)
            continue
        src = io.open(path, encoding='utf-8', errors='surrogateescape').read()
        spec, rep, _ = analyse(src)
        added = 0
        for op, (state, sig, fseq, xors) in sorted(rep.handlers.items()):
            name = labels.get(op)
            if not name:
                continue
            if sig in sigs and sigs[sig] != name:
                conflicts.append((stem, op, name, sigs[sig]))
                continue
            if sig not in sigs:
                added += 1
                # A later build may implement a known operation with a differently
                # shaped handler.  Reuse the operand order already recorded for
                # that operation so the decompiler keeps one set of field names.
                key = (name, len(fseq))
                fields[sig] = by_name.get(key, fseq)
                by_name.setdefault(key, fields[sig])
            sigs[sig] = name
        print('%-22s %3d handler slots, %2d new signatures' % (stem, len(rep.handlers), added))
    for c in conflicts:
        print('CONFLICT %s op%d: %s vs %s' % c)
    out = ['"""Handler fingerprints -> canonical Luau opcode names.',
           '',
           'Generated by tools/gen_signatures.py.  A signature is one opcode handler in',
           'canonical form: identifiers, field slots, state numbers, tuple order and XOR',
           'masks erased, so it stays stable when the protector reshuffles them.',
           '"""', '', 'SIGNATURES = {']
    order = sorted(sigs.items(), key=lambda kv: (kv[1], kv[0]))
    for sig, name in order:
        out.append('    %r:\n        %r,' % (sig, name))
    out.append('}')
    out.append('')
    out.append("# Operand order as seen in the build a signature was first learned from.")
    out.append("# Zipping it against another build's order translates that build's field")
    out.append("# slots into the ones the decompiler expects.")
    out.append('REFERENCE_FIELDS = {')
    for sig, name in order:
        out.append('    %r:\n        %r,' % (sig, fields.get(sig, [])))
    out.append('}')
    io.open(os.path.join(ROOT, 'luauvmp', 'signatures.py'), 'w',
            encoding='utf-8').write('\n'.join(out) + '\n')
    print('total signatures: %d' % len(sigs))


main()
