-- ferret/layers.lua
-- Semantics-preserving, token-level obfuscation passes.
--
--   stringEncrypt : every string literal -> (decoder("<cipher>", salt))
--   numberEncode  : integer literals -> arithmetic that yields the same integer
--
-- Both passes emit constructs whose runtime value is identical to the source,
-- so obfuscated output behaves exactly like the original on any Lua/Luau.

local Emit = require("emit")

local Layers = {}

-- Pure-arithmetic byte XOR (portable across 5.1 / 5.2 / 5.3 / 5.4 / Luau).
local function bxor(a, b)
    local r, p = 0, 1
    while a > 0 or b > 0 do
        local aa, bb = a % 2, b % 2
        if aa ~= bb then r = r + p end
        a = (a - aa) / 2
        b = (b - bb) / 2
        p = p * 2
    end
    return r
end

-- Keystream identical to the one regenerated by the runtime decoder.
-- Uses a Park-Miller LCG (mult 16807, mod 2^31-1); every intermediate product
-- stays below 2^53, so it is exact in Luau/Lua 5.1 doubles AND Lua 5.3/5.4
-- integers -- the obfuscated output decodes identically on every runtime.
local function encryptString(s, salt)
    local out = {}
    local st = salt % 2147483646 + 1
    for i = 1, #s do
        st = (st * 16807) % 2147483647
        local k = st % 256
        out[i] = string.char(bxor(s:byte(i), k))
    end
    return table.concat(out)
end

-- Build the tokens that replace a string literal with a decoder call.
local function decoderCallTokens(fnName, cipher, salt, line)
    local lit = Emit.stringLiteral(cipher)
    return {
        { type = "symbol", value = "(", raw = "(", line = line },
        { type = "name", value = fnName, raw = fnName, line = line },
        { type = "symbol", value = "(", raw = "(", line = line },
        { type = "string", value = cipher, raw = lit, line = line },
        { type = "symbol", value = ",", raw = ",", line = line },
        { type = "number", value = salt, raw = tostring(salt), line = line },
        { type = "symbol", value = ")", raw = ")", line = line },
        { type = "symbol", value = ")", raw = ")", line = line },
    }
end

-- Replace every string token with a wrapped decoder call. Wrapping in parens
-- keeps call-with-string sugar valid: `print "x"` -> `print (dec("..",n))`.
function Layers.stringEncrypt(tokens, rng, names)
    local out = {}
    for _, tok in ipairs(tokens) do
        if tok.type == "string" then
            local salt = rng:range(1, 2147483000)
            local cipher = encryptString(tok.value, salt)
            for _, t in ipairs(decoderCallTokens(names.fs, cipher, salt, tok.line)) do
                out[#out + 1] = t
            end
        else
            out[#out + 1] = tok
        end
    end
    return out
end

-- Replace plain non-negative decimal integer literals with (A-B) where A-B == n.
-- Only touches literals matching ^%d+$ so hex/float/exponent forms are untouched
-- and integer/float typing is preserved.
function Layers.numberEncode(tokens, rng)
    local out = {}
    for _, tok in ipairs(tokens) do
        if tok.type == "number" and type(tok.raw) == "string"
            and tok.raw:match("^%d+$") and #tok.raw <= 9 then
            local n = tonumber(tok.raw)
            local b = rng:range(1, 1000000)
            local a = n + b
            out[#out + 1] = { type = "symbol", value = "(", raw = "(", line = tok.line }
            out[#out + 1] = { type = "number", value = a, raw = tostring(a), line = tok.line }
            out[#out + 1] = { type = "symbol", value = "-", raw = "-", line = tok.line }
            out[#out + 1] = { type = "number", value = b, raw = tostring(b), line = tok.line }
            out[#out + 1] = { type = "symbol", value = ")", raw = ")", line = tok.line }
        else
            out[#out + 1] = tok
        end
    end
    return out
end

-- Runtime prelude: defines the string decoder used by stringEncrypt.
-- Captures string/table primitives into locals at load time so later mutation
-- of the global environment cannot break decoding. Self-contained, single line.
function Layers.buildPrelude(names)
    local fs, sc, sb, tc, cache = names.fs, names.sc, names.sb, names.tc, names.cache
    return table.concat({
        "local " .. sc .. "=string.char",
        "local " .. sb .. "=string.byte",
        "local " .. tc .. "=table.concat",
        "local " .. cache .. "={}",
        "local function " .. fs .. "(e,s)",
        "local ck=s..'|'..e",
        "local cv=" .. cache .. "[ck]",
        "if cv~=nil then return cv end",
        "local t={}",
        "local st=s%2147483646+1",
        "for i=1,#e do",
        "st=(st*16807)%2147483647",
        "local k=st%256",
        "local a,b=" .. sb .. "(e,i),k",
        "local r,p=0,1",
        "while a>0 or b>0 do",
        "local aa,bb=a%2,b%2",
        "if aa~=bb then r=r+p end",
        "a=(a-aa)/2 b=(b-bb)/2 p=p*2",
        "end",
        "t[i]=" .. sc .. "(r)",
        "end",
        "local out=" .. tc .. "(t)",
        cache .. "[ck]=out",
        "return out",
        "end",
    }, "\n")
end

function Layers.makeNames(rng)
    return {
        fs = rng:name(6),
        sc = rng:name(6),
        sb = rng:name(6),
        tc = rng:name(6),
        cache = rng:name(6),
    }
end

return Layers
