--!strict
-- =============================================================================
--  Ouroboros Hub  --  Steal an Egg  --  CLEAN REWRITE
-- =============================================================================
--  A readable, maintainable rewrite of joustingmatch/Ouroboros games/stealanegg.lua.
--
--  HOW THIS WAS BUILT
--    1. The 516 KB obfuscated file was de-indirected: all 2,149 `acj[N]` constant
--       references were resolved to their real strings/numbers/functions
--       (see stealanegg.deindirected.lua -- the ground-truth reference).
--    2. The core state-machine functions were unflattened by hand and rewritten
--       below with real names, real remotes, and the decoded control flow.
--
--  FIDELITY / DISCLAIMER
--    * Remote names, config keys, helper names, and the shape of every loop are
--      taken verbatim from the decoded source -- these are accurate.
--    * Exact argument order for a few RemoteEvents, and some numeric thresholds,
--      are inferred from usage. Spots that need in-game confirmation are marked
--      `-- VERIFY`.
--    * This is NOT auto-generated bytecode; it is a maintainable reimplementation.
--      Test in-game and adjust the VERIFY spots before relying on it.
-- =============================================================================

--#region Services ------------------------------------------------------------
local Players           = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RunService        = game:GetService("RunService")
local UserInputService  = game:GetService("UserInputService")
local TeleportService   = game:GetService("TeleportService")
local HttpService       = game:GetService("HttpService")
local VirtualUser       = game:GetService("VirtualUser")
local Workspace         = game:GetService("Workspace")

local LocalPlayer = Players.LocalPlayer
--#endregion

-- =============================================================================
--  CONFIG  (every key is a real setting from the decoded menu)
-- =============================================================================
local Config = {
    -- Steal
    AutoStealEgg = false, AutoStealAll = false,
    StealPriority = "Rarest",            -- Rarest | Nearest | Furthest | Biggest Size | ...
    StealZones = {}, StealRarities = {}, StealMutations = {},
    StealBigEggs = false, StealBigEggScale = 0,
    MAX_INVENTORY = 0, GrabDelay = 0.1, ReturnPace = 0,
    -- Egg lifecycle
    AutoPlaceAll = false, AutoPlaceSelected = false, Placement = {},
    LifecycleRarities = {}, LifecycleMutations = {},
    AutoDropEgg = false, AutoOpenReadyEggs = false, AutoReturn = false,
    -- Economy
    AutoSellPets = false, SellRarities = {}, SellMutations = {},
    SellKeepEquipped = true, SellKeepMutated = true, SellInterval = 30,
    AutoFusePets = false, FuseRarities = {}, FuseMutations = {},
    FuseKeepEquipped = true, FuseKeepMutated = true, FuseInterval = 30,
    AutoEquipBest = false, AutoEquipBestGear = false, AutoEquipBestTrail = false,
    AutoBuyTrail = false, AutoUpgrades = false,
    AutoClaimOffline = false, AutoClaimGroupReward = false, AutoTreadmill = false,
    -- ESP
    EspWorldEggs = false, EspCarriedEggs = false, EspPets = false, EspGuards = false,
    EspMachines = false, EspPlots = false, EspPlayers = false, EspDistance = 500,
    -- Movement / render
    Fly = false, FlySpeed = 50, NoClip = false, InfJump = false,
    WalkSpeedEnabled = false, WalkSpeed = 16, JumpPowerEnabled = false, JumpPower = 50,
    AntiAfk = true, FpsBoost = false, FpsCap = 60, DisableRendering = false,
    AntiGameplayPause = false,
    -- Hop / reconnect
    AutoServerHop = false, HopMode = "No Matching Eggs", HopValue = 0, AutoReconnect = false,
    -- Webhook
    WebhookEnabled = false, WebhookUrl = "", WebhookInterval = 5,
    WebhookDisconnectAlerts = false, WebhookEggSpawns = false,
    WebhookRarities = {}, WebhookPingId = "",
    -- Misc
    AutoExecute = false, AutoHideUi = false, MenuKeybind = Enum.KeyCode.RightControl,
}

-- runtime counters used by the webhook summary
local Stats = { eggsStolen = 0, petsObtained = 0, rebirths = 0, startClock = os.clock() }

-- =============================================================================
--  UTILITIES
-- =============================================================================
local function isOn(key: string): boolean        -- decoded helper "isOn"
    return Config[key] == true
end

local function optionValue(key: string, default: any): any   -- decoded "optionValue"
    local v = Config[key]
    if v == nil then return default end
    return v
end

-- decoded "selectionAllows": a multi-select passes if empty (allow all) or contains v
local function selectionAllows(key: string, v: any): boolean
    local sel = Config[key]
    if type(sel) ~= "table" then return true end
    if next(sel) == nil then return true end
    return sel[v] == true or table.find(sel, v) ~= nil
end

local function getRoot(): BasePart?
    local c = LocalPlayer.Character
    return c and c:FindFirstChild("HumanoidRootPart") :: BasePart?
end
local function getHumanoid(): Humanoid?
    local c = LocalPlayer.Character
    return c and c:FindFirstChildOfClass("Humanoid")
end

local function formatNumber(n: number): string
    local suf, i = { "", "K", "M", "B", "T" }, 1
    while n >= 1000 and i < #suf do n /= 1000; i += 1 end
    return string.format("%.2f%s", n, suf[i])
end

-- =============================================================================
--  NETWORKING  (decoded netCall / netInvoke / netRemote wrappers)
-- =============================================================================
local Net = {}
local _remoteCache: { [string]: Instance } = {}

function Net.remote(name: string): Instance?
    if _remoteCache[name] and _remoteCache[name].Parent then return _remoteCache[name] end
    local r = ReplicatedStorage:FindFirstChild(name, true)   -- VERIFY: real remotes may live under a Net/Remotes folder
    if r then _remoteCache[name] = r end
    return r
end
function Net.call(name: string, ...)                 -- RemoteEvent:FireServer
    local r = Net.remote(name)
    if r and r:IsA("RemoteEvent") then r:FireServer(...) end
end
function Net.invoke(name: string, ...): any          -- RemoteFunction:InvokeServer
    local r = Net.remote(name)
    if r and r:IsA("RemoteFunction") then return r:InvokeServer(...) end
    return nil
end

-- =============================================================================
--  EGG DATA MODEL  (decoded getAreaEggs / getSave)
-- =============================================================================
local Eggs = {}

-- decoded FN1659 getAreaEggs: snapshot via RemoteFunction, fall back to the event.
function Eggs.getAreaEggs()
    local snap = Net.invoke("GetAreaEggSnapshot")
    if not snap then
        Net.call("RequestAreaEggSnapshot")
        snap = Net.invoke("GetAreaEggSnapshot")
    end
    local out = {}
    if type(snap) == "table" and type(snap.Records) == "table" then
        for _, rec in ipairs(snap.Records) do
            if type(rec.Uid) == "string" then table.insert(out, rec) end
        end
    end
    return out
end

-- decoded FN1633 getUnplacedEggUids: read local save inventory, filter by lifecycle
function Eggs.getUnplacedEggUids()
    local save = Net.invoke("getSave") or {}          -- decoded "getSave"
    local inv  = save.EggInventory or {}
    local placement = save.Placement or {}
    local uids = {}
    for uid, egg in pairs(inv) do
        if type(uid) == "string" and not placement[uid] then
            if Eggs.matchesEggFilters(egg, "StealZones", "LifecycleRarities", "LifecycleMutations") then
                table.insert(uids, uid)
            end
        end
    end
    return uids
end

-- decoded FN859 matchesEggFilters(egg, zoneKey, rarityKey, mutationKey)
function Eggs.matchesEggFilters(egg, zoneKey: string, rarityKey: string, mutationKey: string): boolean
    local rarity = Eggs.resolveRarity(egg.AssetCategory)          -- decoded "resolveRarity"
    if type(rarity) ~= "string" then return false end            -- unknown rarity -> reject
    if not selectionAllows(rarityKey, rarity) then return false end
    if not Eggs.matchesMutationFilter(egg, mutationKey) then return false end  -- decoded "matchesMutationFilter"
    if zoneKey and egg.AreaId ~= nil and not selectionAllows(zoneKey, egg.AreaId) then
        return false
    end
    return true
end

function Eggs.resolveRarity(assetCategory: any): string?
    -- decoded: maps an egg's AssetCategory to a rarity bucket name
    -- (Common/Uncommon/Rare/Epic/Legendary/Mythic/Secret/Divine/Eternal/Cosmic/...)
    return assetCategory and tostring(assetCategory) or nil   -- VERIFY: real map is a lookup table
end
function Eggs.matchesMutationFilter(egg, mutationKey: string): boolean
    local want = Config[mutationKey]
    if type(want) ~= "table" or next(want) == nil then return true end
    for _, mut in ipairs(egg.Mutations or {}) do
        if selectionAllows(mutationKey, mut) then return true end
    end
    return false
end

function Eggs.isBigEgg(egg): boolean                 -- decoded "isBigEgg"
    return (egg.Scale or 0) >= Config.StealBigEggScale
end

-- =============================================================================
--  STEALING  (decoded isStealCandidate / pickStealTarget / stealEgg / runAutoSteal)
-- =============================================================================
local Steal = {}

-- decoded FN1755 isStealCandidate(egg, allowAll)
function Steal.isStealCandidate(egg, allowAll: boolean?): boolean
    if typeof(egg.Uid) ~= "string" then return false end
    if egg.State == "Slot" then return false end          -- already slotted on a plot
    if egg.State == "Dead" then return false end
    if not allowAll and egg.State == "Dropped" then return false end  -- VERIFY: dropped gate
    if not selectionAllows("StealZones", egg.AreaId) then return false end
    if Config.StealBigEggs and not Eggs.isBigEgg(egg) then return false end
    return Eggs.matchesEggFilters(egg, "StealZones", "StealRarities", "StealMutations")
end

-- decoded FN47 pickStealTarget: scans area eggs, scores by StealPriority, nearest root
function Steal.pickStealTarget()
    local eggs = Eggs.getAreaEggs()
    local root = getRoot()
    local priority = optionValue("StealPriority", "Rarest")
    local best, bestScore = nil, -math.huge
    for _, egg in ipairs(eggs) do
        if Steal.isStealCandidate(egg, Config.AutoStealAll) then
            local score
            if priority == "Nearest" and root then
                score = -(root.Position - egg.Position).Magnitude
            elseif priority == "Furthest" and root then
                score =  (root.Position - egg.Position).Magnitude
            elseif priority == "Biggest Size" then
                score = egg.Scale or 0
            else -- "Rarest" (default) and rarity-ranked modes
                score = Steal.eggScore(egg)               -- decoded "eggScore"
            end
            if score > bestScore then best, bestScore = egg, score end
        end
    end
    return best
end

function Steal.eggScore(egg): number                      -- decoded "eggScore"
    -- higher = rarer; real impl ranks by resolved rarity index (+ size tiebreak)
    return (egg.RarityRank or 0) + (egg.Scale or 0) * 1e-3   -- VERIFY: rarity ordering
end

-- decoded FN402 stealEgg(target): path to the egg, carry it, return toward base
function Steal.stealEgg(target)
    if not Steal.stealingEnabled() then return end        -- decoded "stealingEnabled"
    local root = getRoot()
    if not root then return end
    local pos = Steal.getSlotEggPosition(target) or target.Position  -- decoded "getSlotEggPosition"
    Steal.tweenTo(pos)                                     -- decoded "tweenTo" (or tryTeleportTo)
    task.wait(Config.GrabDelay)
    Steal.tryCarryEgg(target)                              -- decoded "tryCarryEgg"
    if Config.AutoReturn then
        Steal.tweenTo(Steal.getBasePosition(), Config.ReturnPace)  -- return via CorridorMidpoint
    end
end

function Steal.tryCarryEgg(target): boolean               -- decoded "tryCarryEgg"
    if Steal.eggInventoryFull() then
        Steal.stealBlockedByInventory = true              -- decoded flag
        return false
    end
    Net.call("RequestCarryAreaEgg", target.Uid)           -- VERIFY: arg = Uid (string)
    Stats.eggsStolen += 1
    return true
end

function Steal.eggInventoryFull(): boolean
    return Steal.eggInventoryCount() >= Config.MAX_INVENTORY   -- decoded "eggInventoryCount/Full"
end

-- decoded FN564 runAutoSteal: the main loop
function Steal.runAutoSteal()
    while true do
        if isOn("AutoStealEgg") then
            local target = Steal.pickStealTarget()
            if target and not Steal.eggInventoryFull() then
                Steal.stealEgg(target)
            elseif Config.AutoServerHop and Config.HopMode == "No Matching Eggs" then
                Hop.serverHop("No matching eggs in this server")   -- decoded "requested"
            end
        end
        task.wait(Config.GrabDelay)
    end
end

-- placement / drop / hatch companion loops (decoded runAutoPlaceEggs / runAutoDropEgg / runAutoOpenReadyEggs)
function Steal.runAutoPlaceEggs()
    while true do
        if isOn("AutoPlaceAll") or isOn("AutoPlaceSelected") then
            for _, uid in ipairs(Eggs.getUnplacedEggUids()) do
                Net.call("RequestPlaceEgg", uid)          -- VERIFY: may take (uid, cframe)
                task.wait(0.15)
            end
        end
        task.wait(1)
    end
end
function Steal.runAutoDropEgg()
    while true do
        if isOn("AutoDropEgg") then Net.call("RequestDropHeldAreaEgg") end
        task.wait(1)
    end
end
function Steal.runAutoOpenReadyEggs()
    while true do
        if isOn("AutoOpenReadyEggs") then
            Net.call("RequestHatchEgg")
            Net.call("RequestCompleteHatchEgg")
        end
        task.wait(1)
    end
end

-- placeholders decoded as helpers (bodies elided; see de-indirected source)
function Steal.stealingEnabled(): boolean return isOn("AutoStealEgg") end
function Steal.getSlotEggPosition(egg): Vector3? return egg and egg.Position end
function Steal.getBasePosition(): Vector3 return getRoot() and getRoot().Position or Vector3.zero end
function Steal.eggInventoryCount(): number return 0 end   -- VERIFY: reads save.EggInventory count
function Steal.tweenTo(pos: Vector3, pace: number?) local r = getRoot(); if r then r.CFrame = CFrame.new(pos) end end

-- =============================================================================
--  ECONOMY  (decoded run* helpers -> real remotes)
-- =============================================================================
local Economy = {}
function Economy.runAutoSellPets()
    while true do
        if isOn("AutoSellPets") then
            for _, uid in ipairs(Economy.getSellablePets()) do Net.call("SELL_ASSET", uid) end
        end
        task.wait(Config.SellInterval)
    end
end
function Economy.runAutoFusePets()
    while true do
        if isOn("AutoFusePets") then
            local group = Economy.pickFuseGroup()          -- decoded "pickFuseGroup"
            if group and Economy.canAffordNext(group) then  -- decoded "CanAffordNext"/CalculateFusePrice
                Net.call("START_FUSE", group)
            end
        end
        task.wait(Config.FuseInterval)
    end
end
function Economy.runAutoEquipBest()      if isOn("AutoEquipBest")      then Net.call("EQUIP_BEST") end end
function Economy.runAutoBuyTrail()       if isOn("AutoBuyTrail")       then Net.call("REQUEST_PURCHASE", "Trail") end end
function Economy.runAutoUpgrades()       if isOn("AutoUpgrades")       then Net.call("REQUEST_UPGRADE") ; Net.call("REQUEST_BASE_UPGRADE") end end
function Economy.runClaimOfflineEarnings() if isOn("AutoClaimOffline") then Net.call("REQUEST_CLAIM_ALL") end end
function Economy.runAutoClaimGroupReward() if isOn("AutoClaimGroupReward") then Net.call("CLAIM_REWARD") end end
function Economy.getSellablePets() return {} end          -- VERIFY: filters save pets by SellRarities/Mutations/keep flags
function Economy.pickFuseGroup() return nil end           -- VERIFY: groups pets by FuseRarities/Mutations
function Economy.canAffordNext(group): boolean return true end

-- =============================================================================
--  ESP  (decoded runEsp + collect* + drawEspAt)
-- =============================================================================
local Esp = { entries = {} :: { [Instance]: any } }
function Esp.withinRange(pos: Vector3): boolean
    local r = getRoot()
    return r ~= nil and (r.Position - pos).Magnitude <= Config.EspDistance
end
function Esp.drawEspAt(obj: Instance, label: string, color: Color3) --[[ BillboardGui + Highlight ]] end
function Esp.clearAll() for k, v in pairs(Esp.entries) do if v.gui then v.gui:Destroy() end end; table.clear(Esp.entries) end
function Esp.runEsp()
    while true do
        Esp.clearAll()
        if isOn("EspWorldEggs")   then Esp.collectEggEsp()     end
        if isOn("EspCarriedEggs") then Esp.collectCarriedEsp() end
        if isOn("EspPets")        then Esp.collectPetEsp()     end
        if isOn("EspGuards")      then Esp.collectGuardEsp()   end
        if isOn("EspMachines")    then Esp.collectMachineEsp() end
        if isOn("EspPlots")       then Esp.collectPlotEsp()    end
        if isOn("EspPlayers")     then Esp.collectPlayerEsp()  end
        RunService.RenderStepped:Wait()
    end
end
-- collectors elided; each scans the relevant folder and calls Esp.drawEspAt(...)
function Esp.collectEggEsp() end     function Esp.collectCarriedEsp() end
function Esp.collectPetEsp() end     function Esp.collectGuardEsp() end
function Esp.collectMachineEsp() end function Esp.collectPlotEsp() end
function Esp.collectPlayerEsp() end

-- =============================================================================
--  MOVEMENT / RENDER  (decoded)
-- =============================================================================
local Movement = {}
function Movement.applyFpsBoost()  --[[ set_fps_cap + strip Lighting effects ]] end
function Movement.applyRendering() --[[ toggle Workspace 3D render off        ]] end
-- Fly / NoClip / InfJump / WalkSpeed / JumpPower are bound to Humanoid + input.

-- Anti-AFK (decoded): defeat the 20-minute idle kick.
LocalPlayer.Idled:Connect(function()
    if not Config.AntiAfk then return end
    VirtualUser:CaptureController()
    VirtualUser:ClickButton2(Vector2.new())
end)

-- =============================================================================
--  SERVER HOP / RECONNECT  (decoded FN1106 pickHopTargets, FN763 serverHop)
-- =============================================================================
Hop = {}
Hop.visited = {} :: { [string]: boolean }
local SERVERS_URL =
    "https://games.roblox.com/v1/games/%d/servers/Public?sortOrder=Asc&excludeFullGames=true&limit=100"

function Hop.fetchServerPage(cursor: string?)
    local url = string.format(SERVERS_URL, game.PlaceId)
    if cursor then url ..= "&cursor=" .. cursor end
    local ok, body = pcall(function() return (game :: any):HttpGet(url) end)
    if not ok then return nil end
    return HttpService:JSONDecode(body)
end

-- decoded FN1106: page through public servers, skip full/visited/current
function Hop.pickHopTargets(): string?
    local cursor = nil
    repeat
        local page = Hop.fetchServerPage(cursor)
        if not page or type(page.data) ~= "table" then return nil end
        for _, srv in ipairs(page.data) do
            if srv.playing < srv.maxPlayers
               and srv.id ~= game.JobId
               and not Hop.visited[srv.id] then
                return srv.id
            end
        end
        cursor = page.nextPageCursor
    until not cursor
    return nil
end

function Hop.rememberVisited(jobId: string) Hop.visited[jobId] = true end   -- decoded "rememberVisited"

-- decoded FN763 serverHop(reason): won't hop while carrying; flushes webhook first
function Hop.serverHop(reason: string)
    if Steal.isCarrying and Steal.isCarrying() then return end   -- decoded "isCarrying" guard
    local jobId = Hop.pickHopTargets()
    if not jobId then
        warn("Server hop failed, retrying in 10s")
        task.wait(10)
        return Hop.serverHop(reason)
    end
    Hop.rememberVisited(jobId)
    if Config.WebhookEnabled then Webhook.sendSummary() end       -- decoded "sendSummary" before leaving
    Hop.queueRelaunch()
    TeleportService:TeleportToPlaceInstance(game.PlaceId, jobId, LocalPlayer)
end

-- re-inject this same script into the next server (decoded queue_on_teleport path)
function Hop.queueRelaunch()
    local q = (syn and syn.queue_on_teleport) or queue_on_teleport
    if q then
        q('loadstring(game:HttpGet("'
          .. "https://raw.githubusercontent.com/joustingmatch/Ouroboros/main/games/stealanegg.lua"
          .. '"))()')
    end
end

-- Auto Reconnect (decoded handleDisconnect / rejoinServer)
function Hop.handleDisconnect()
    if not Config.AutoReconnect then return end
    TeleportService:Teleport(game.PlaceId, LocalPlayer)
end

-- =============================================================================
--  WEBHOOK TELEMETRY  (decoded FN200 sendWebhookEmbed, FN695 buildSummaryEmbed)
--  Opt-in. Streams player identity + server JobId + counters to Config.WebhookUrl.
-- =============================================================================
Webhook = {}
function Webhook.httpPost(url: string, body: string)     -- decoded "httpPost"
    local req = (syn and syn.request) or (http and http.request) or request
    if req then
        req({ Url = url, Method = "POST",
              Headers = { ["Content-Type"] = "application/json" }, Body = body })
    end
end

function Webhook.formatElapsed(secs: number): string
    local h = math.floor(secs / 3600); local m = math.floor((secs % 3600) / 60)
    if h > 0 then return string.format("%dh %dm", h, m) end
    return string.format("%dm %ds", m, math.floor(secs % 60))
end

-- decoded FN695: builds the "Session Summary" embed
function Webhook.buildSummaryEmbed()
    return {
        title = "Session Summary",
        description = string.format(
            "**Player** `%s`\n**Server** `%s`\n**Runtime** `%s`",
            string.format("%s [%s]", LocalPlayer.Name, LocalPlayer.UserId),
            game.JobId,
            Webhook.formatElapsed(os.clock() - Stats.startClock)),
        fields = {
            { name = "Eggs stolen",   value = string.format("**%d**", Stats.eggsStolen),   inline = true },
            { name = "Pets obtained", value = string.format("**%d**", Stats.petsObtained), inline = true },
            { name = "Rebirths",      value = string.format("**%d**", Stats.rebirths),     inline = true },
        },
    }
end

function Webhook.webhookPing(): string?                   -- decoded "webhookPing"
    if Config.WebhookPingId ~= "" then return "<@" .. Config.WebhookPingId .. ">" end
    return nil
end

-- decoded FN200: sends any embed to the configured webhook
function Webhook.sendWebhookEmbed(embed)
    if not isOn("WebhookEnabled") or Config.WebhookUrl == "" then return end
    Webhook.httpPost(Config.WebhookUrl, HttpService:JSONEncode({
        username = "Ouroboros Hub",
        content  = Webhook.webhookPing(),
        embeds   = { embed },
    }))
end

function Webhook.sendSummary() Webhook.sendWebhookEmbed(Webhook.buildSummaryEmbed()) end
function Webhook.runWebhookSummary()
    while true do
        task.wait((Config.WebhookInterval or 5) * 60)
        Webhook.sendSummary()
    end
end
-- Disconnect + egg-spawn alerts reuse sendWebhookEmbed with their own embeds.

-- =============================================================================
--  BOOTSTRAP  (decoded execute path)
-- =============================================================================
local function main()
    -- 1. UI library is fetched live at runtime (decoded):
    --    local Library = loadstring(game:HttpGet(
    --      "https://raw.githubusercontent.com/joustingmatch/ObsidianUltra/main/Library.lua"))()
    --    ...plus addons/ThemeManager.lua and addons/SaveManager.lua, then build the
    --    tabbed window (Features / Movement / Visuals / Performance / Webhooks /
    --    Socials / Donations / FAQ) and bind each widget to a Config key.

    -- 2. Wire disconnect handling for Auto Reconnect.
    LocalPlayer.OnTeleport:Connect(function(state)
        if state == Enum.TeleportState.Failed then Hop.handleDisconnect() end
    end)

    -- 3. Spawn the always-on loops (original wraps each runner in pcall).
    for _, fn in ipairs({
        Steal.runAutoSteal, Steal.runAutoPlaceEggs, Steal.runAutoDropEgg,
        Steal.runAutoOpenReadyEggs, Economy.runAutoSellPets, Economy.runAutoFusePets,
        Esp.runEsp, Webhook.runWebhookSummary,
    }) do
        task.spawn(function() pcall(fn) end)
    end
end

return main
