"""
Nano AI Code Generator – produces complete, production-quality scripts
for any language, UI, CSS animations, Three.js 3D, Roblox, and more.
"""

import re
import random

# ─── Template registry ────────────────────────────────────────────────────────

def generate(request: str) -> str:
    """Route a generation request to the right template."""
    t = request.lower()

    # 3D / Three.js
    if any(k in t for k in ["3d", "three.js", "threejs", "three js", "webgl", "cube", "scene"]):
        return _gen_threejs(t)

    # Animation
    if any(k in t for k in ["animation", "animate", "css anim", "keyframe", "transition", "loading spinner", "spinner"]):
        return _gen_css_animation(t)

    # UI / website / landing page
    if any(k in t for k in ["ui", "landing page", "website", "webpage", "dashboard", "portfolio", "card", "navbar", "modal"]):
        return _gen_html_ui(t)

    # Roblox / Lua game script
    if any(k in t for k in ["roblox", "luau", "obby", "gui", "roblox script", "roblox game"]):
        return _gen_roblox(t)

    # Python scripts
    if any(k in t for k in ["python", "flask", "fastapi", "django", "scraper", "web scraper"]):
        return _gen_python(t)

    # JavaScript / Node / React
    if any(k in t for k in ["javascript", "react", "node", "express", "vue", "next.js"]):
        return _gen_javascript(t)

    # REST API
    if any(k in t for k in ["api", "rest api", "endpoint", "server", "backend"]):
        return _gen_rest_api(t)

    # Database
    if any(k in t for k in ["sql", "database", "sqlite", "mysql", "postgres", "schema"]):
        return _gen_sql(t)

    # General: just produce an example in the best matching language
    return _gen_general(request)


# ─── Three.js 3D ─────────────────────────────────────────────────────────────

def _gen_threejs(hint: str) -> str:
    shape = "cube"
    color = "0x6c63ff"
    if "sphere" in hint:
        shape = "sphere"
    if "torus" in hint or "donut" in hint:
        shape = "torus"
    if "pyramid" in hint or "cone" in hint:
        shape = "cone"

    geometry = {
        "cube":   "new THREE.BoxGeometry(1, 1, 1)",
        "sphere": "new THREE.SphereGeometry(0.7, 32, 32)",
        "torus":  "new THREE.TorusGeometry(0.6, 0.25, 16, 100)",
        "cone":   "new THREE.ConeGeometry(0.6, 1.2, 32)",
    }[shape]

    code = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Nano AI — 3D Scene</title>
  <style>
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{ background: #0a0a1a; overflow: hidden; }}
    canvas {{ display: block; }}
    #info {{
      position: absolute; top: 20px; left: 50%;
      transform: translateX(-50%);
      color: #aaa; font-family: 'Segoe UI', sans-serif;
      font-size: 14px; pointer-events: none;
    }}
  </style>
</head>
<body>
  <div id="info">Drag to rotate · Scroll to zoom · Generated by Nano AI</div>
  <script src="https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/three@0.160.0/examples/js/controls/OrbitControls.js"></script>
  <script>
    // ── Scene setup ──────────────────────────────────────────────
    const scene    = new THREE.Scene();
    scene.fog      = new THREE.FogExp2(0x0a0a1a, 0.05);

    const camera   = new THREE.PerspectiveCamera(60, innerWidth / innerHeight, 0.1, 100);
    camera.position.set(0, 0.5, 3);

    const renderer = new THREE.WebGLRenderer({{ antialias: true }});
    renderer.setSize(innerWidth, innerHeight);
    renderer.setPixelRatio(devicePixelRatio);
    renderer.shadowMap.enabled = true;
    document.body.appendChild(renderer.domElement);

    // ── Controls ─────────────────────────────────────────────────
    const controls = new THREE.OrbitControls(camera, renderer.domElement);
    controls.enableDamping = true;
    controls.dampingFactor = 0.05;

    // ── Lights ───────────────────────────────────────────────────
    scene.add(new THREE.AmbientLight(0xffffff, 0.4));
    const dirLight = new THREE.DirectionalLight(0xffffff, 1.2);
    dirLight.position.set(5, 10, 5);
    dirLight.castShadow = true;
    scene.add(dirLight);

    const pointLight = new THREE.PointLight({color}, 2, 10);
    pointLight.position.set(-2, 2, 2);
    scene.add(pointLight);

    // ── Main object ──────────────────────────────────────────────
    const geometry = {geometry};
    const material = new THREE.MeshStandardMaterial({{
      color:     {color},
      metalness: 0.4,
      roughness: 0.3,
      emissive:  0x1a1040,
    }});
    const mesh = new THREE.Mesh(geometry, material);
    mesh.castShadow    = true;
    mesh.receiveShadow = true;
    scene.add(mesh);

    // ── Wireframe overlay ────────────────────────────────────────
    const wire = new THREE.Mesh(
      geometry,
      new THREE.MeshBasicMaterial({{ color: 0xffffff, wireframe: true, opacity: 0.08, transparent: true }})
    );
    scene.add(wire);

    // ── Particle field ───────────────────────────────────────────
    const particleGeo = new THREE.BufferGeometry();
    const count = 1500;
    const pos   = new Float32Array(count * 3);
    for (let i = 0; i < count * 3; i++) pos[i] = (Math.random() - 0.5) * 20;
    particleGeo.setAttribute('position', new THREE.BufferAttribute(pos, 3));
    scene.add(new THREE.Points(
      particleGeo,
      new THREE.PointsMaterial({{ color: 0x6c63ff, size: 0.04, transparent: true, opacity: 0.6 }})
    ));

    // ── Floor ────────────────────────────────────────────────────
    const floor = new THREE.Mesh(
      new THREE.PlaneGeometry(20, 20),
      new THREE.MeshStandardMaterial({{ color: 0x111122, roughness: 1 }})
    );
    floor.rotation.x = -Math.PI / 2;
    floor.position.y = -1.2;
    floor.receiveShadow = true;
    scene.add(floor);

    // ── Grid ─────────────────────────────────────────────────────
    scene.add(new THREE.GridHelper(20, 20, 0x222244, 0x222244));

    // ── Animation loop ───────────────────────────────────────────
    const clock = new THREE.Clock();
    function animate() {{
      requestAnimationFrame(animate);
      const t = clock.getElapsedTime();
      mesh.rotation.x = t * 0.4;
      mesh.rotation.y = t * 0.6;
      wire.rotation.copy(mesh.rotation);
      pointLight.position.x = Math.sin(t) * 3;
      pointLight.position.z = Math.cos(t) * 3;
      controls.update();
      renderer.render(scene, camera);
    }}
    animate();

    // ── Responsive ──────────────────────────────────────────────
    window.addEventListener('resize', () => {{
      camera.aspect = innerWidth / innerHeight;
      camera.updateProjectionMatrix();
      renderer.setSize(innerWidth, innerHeight);
    }});
  </script>
</body>
</html>"""
    return _wrap_output(f"Three.js 3D Scene ({shape})", "html", code)


# ─── CSS Animations ───────────────────────────────────────────────────────────

def _gen_css_animation(hint: str) -> str:
    code = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Nano AI — CSS Animations</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      min-height: 100vh;
      background: #0d0d1a;
      display: flex;
      flex-wrap: wrap;
      align-items: center;
      justify-content: center;
      gap: 60px;
      padding: 60px 40px;
      font-family: 'Segoe UI', sans-serif;
    }

    h1 {
      width: 100%;
      text-align: center;
      color: #7c6fff;
      font-size: 1.4rem;
      letter-spacing: 4px;
      text-transform: uppercase;
      margin-bottom: -20px;
    }

    .card {
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 16px;
      color: #888;
      font-size: 0.8rem;
      letter-spacing: 1px;
    }

    /* ── 1. Pulse ring ─────────────────────────────── */
    .pulse {
      width: 70px; height: 70px;
      background: #6c63ff;
      border-radius: 50%;
      animation: pulse 1.5s ease-in-out infinite;
    }
    @keyframes pulse {
      0%, 100% { transform: scale(1);    box-shadow: 0 0 0  0 rgba(108,99,255,.6); }
      50%       { transform: scale(1.1); box-shadow: 0 0 0 20px rgba(108,99,255,0); }
    }

    /* ── 2. Spinner ────────────────────────────────── */
    .spinner {
      width: 60px; height: 60px;
      border: 5px solid #1e1e3a;
      border-top-color: #6c63ff;
      border-right-color: #ff6584;
      border-radius: 50%;
      animation: spin 0.9s linear infinite;
    }
    @keyframes spin { to { transform: rotate(360deg); } }

    /* ── 3. Typing cursor ──────────────────────────── */
    .typing {
      font-size: 1.1rem;
      color: #ccc;
      border-right: 3px solid #6c63ff;
      white-space: nowrap;
      overflow: hidden;
      width: 12ch;
      animation: typing 2.5s steps(12) infinite,
                 blink  0.6s step-end  infinite alternate;
    }
    @keyframes typing {
      0%, 10%  { width: 0; }
      50%, 90% { width: 12ch; }
      100%     { width: 0; }
    }
    @keyframes blink { from { border-color: transparent; } to { border-color: #6c63ff; } }

    /* ── 4. Floating orbs ──────────────────────────── */
    .orbs { position: relative; width: 80px; height: 80px; }
    .orb  {
      position: absolute; width: 20px; height: 20px;
      border-radius: 50%; top: 30px; left: 30px;
      animation: orbit 1.6s linear infinite;
    }
    .orb:nth-child(1) { background: #6c63ff; animation-delay: 0s; }
    .orb:nth-child(2) { background: #ff6584; animation-delay: -.53s; }
    .orb:nth-child(3) { background: #43e97b; animation-delay: -1.06s; }
    @keyframes orbit {
      0%   { transform: rotate(0deg)   translateX(30px) rotate(0deg);   }
      100% { transform: rotate(360deg) translateX(30px) rotate(-360deg); }
    }

    /* ── 5. Morphing blob ──────────────────────────── */
    .blob {
      width: 80px; height: 80px;
      background: linear-gradient(135deg, #6c63ff, #ff6584);
      border-radius: 60% 40% 30% 70% / 60% 30% 70% 40%;
      animation: morph 4s ease-in-out infinite;
    }
    @keyframes morph {
      0%,100% { border-radius: 60% 40% 30% 70% / 60% 30% 70% 40%; }
      25%     { border-radius: 30% 60% 70% 40% / 50% 60% 30% 60%; }
      50%     { border-radius: 50% 50% 20% 80% / 25% 80% 20% 75%; }
      75%     { border-radius: 67% 33% 47% 53% / 37% 20% 80% 63%; }
    }

    /* ── 6. Progress bar ───────────────────────────── */
    .progress-wrap {
      width: 140px; height: 8px;
      background: #1e1e3a;
      border-radius: 4px;
      overflow: hidden;
    }
    .progress-bar {
      height: 100%;
      background: linear-gradient(90deg, #6c63ff, #ff6584);
      border-radius: 4px;
      animation: progress 2s ease-in-out infinite;
    }
    @keyframes progress {
      0%   { width: 0%;    opacity: 1; }
      80%  { width: 100%;  opacity: 1; }
      100% { width: 100%;  opacity: 0; }
    }

    /* ── 7. Glowing text ───────────────────────────── */
    .glow {
      font-size: 1.8rem;
      font-weight: bold;
      color: #fff;
      animation: glow 2s ease-in-out infinite alternate;
      letter-spacing: 4px;
    }
    @keyframes glow {
      from { text-shadow: 0 0 4px #6c63ff, 0 0 10px #6c63ff; }
      to   { text-shadow: 0 0 20px #ff6584, 0 0 60px #ff6584; }
    }

    /* ── 8. Bouncing dots ──────────────────────────── */
    .dots { display: flex; gap: 8px; }
    .dot  {
      width: 14px; height: 14px;
      background: #6c63ff; border-radius: 50%;
      animation: bounce 1s ease-in-out infinite;
    }
    .dot:nth-child(2) { background: #ff6584; animation-delay: .15s; }
    .dot:nth-child(3) { background: #43e97b; animation-delay: .30s; }
    @keyframes bounce {
      0%,100% { transform: translateY(0);    }
      50%     { transform: translateY(-20px); }
    }
  </style>
</head>
<body>
  <h1>Nano AI — CSS Animations</h1>

  <div class="card"><div class="pulse"></div>Pulse Ring</div>
  <div class="card"><div class="spinner"></div>Spinner</div>
  <div class="card"><div class="typing">Hello World!</div>Typing Cursor</div>
  <div class="card"><div class="orbs"><div class="orb"></div><div class="orb"></div><div class="orb"></div></div>Orbit</div>
  <div class="card"><div class="blob"></div>Morphing Blob</div>
  <div class="card"><div class="progress-wrap"><div class="progress-bar"></div></div>Progress</div>
  <div class="card"><div class="glow">NANO</div>Glow Text</div>
  <div class="card"><div class="dots"><div class="dot"></div><div class="dot"></div><div class="dot"></div></div>Bounce</div>
</body>
</html>"""
    return _wrap_output("CSS Animations Showcase", "html", code)


# ─── HTML UI / Landing Page ────────────────────────────────────────────────────

def _gen_html_ui(hint: str) -> str:
    if "dashboard" in hint:
        return _gen_dashboard()
    if "portfolio" in hint:
        return _gen_portfolio()
    if "card" in hint:
        return _gen_cards()
    return _gen_landing_page()


def _gen_landing_page() -> str:
    code = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Nano AI — Landing Page</title>
  <style>
    :root {
      --primary: #6c63ff;
      --accent:  #ff6584;
      --bg:      #0d0d1a;
      --surface: #14142a;
      --text:    #e0e0f0;
      --muted:   #888;
    }
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    html { scroll-behavior: smooth; }
    body { background: var(--bg); color: var(--text); font-family: 'Segoe UI', system-ui, sans-serif; }

    /* Nav */
    nav {
      position: fixed; top: 0; width: 100%; padding: 16px 40px;
      display: flex; justify-content: space-between; align-items: center;
      background: rgba(13,13,26,.8); backdrop-filter: blur(12px);
      border-bottom: 1px solid #1e1e3a; z-index: 100;
    }
    .logo { font-size: 1.4rem; font-weight: 700; color: var(--primary); letter-spacing: 2px; }
    .nav-links { display: flex; gap: 28px; list-style: none; }
    .nav-links a { color: var(--muted); text-decoration: none; font-size: .9rem; transition: color .2s; }
    .nav-links a:hover { color: var(--text); }
    .cta-btn {
      padding: 10px 22px; background: var(--primary); color: #fff;
      border: none; border-radius: 8px; cursor: pointer; font-size: .9rem;
      transition: transform .2s, box-shadow .2s;
    }
    .cta-btn:hover { transform: translateY(-2px); box-shadow: 0 8px 30px rgba(108,99,255,.4); }

    /* Hero */
    .hero {
      min-height: 100vh; display: flex; align-items: center; justify-content: center;
      text-align: center; padding: 120px 40px 80px;
      background: radial-gradient(ellipse at top, #1a1040 0%, var(--bg) 70%);
    }
    .hero-badge {
      display: inline-block; padding: 4px 14px;
      background: rgba(108,99,255,.15); border: 1px solid var(--primary);
      border-radius: 20px; font-size: .8rem; color: var(--primary);
      margin-bottom: 24px; letter-spacing: 1px;
    }
    .hero h1 { font-size: clamp(2.5rem, 6vw, 5rem); line-height: 1.1; margin-bottom: 20px; }
    .hero h1 span { color: var(--primary); }
    .hero p  { font-size: 1.15rem; color: var(--muted); max-width: 560px; margin: 0 auto 36px; line-height: 1.7; }
    .hero-btns { display: flex; gap: 16px; justify-content: center; flex-wrap: wrap; }
    .btn-outline {
      padding: 12px 28px; border: 1px solid #333; color: var(--text);
      background: transparent; border-radius: 8px; cursor: pointer; font-size: 1rem;
      transition: border-color .2s, background .2s;
    }
    .btn-outline:hover { border-color: var(--primary); background: rgba(108,99,255,.1); }
    .btn-primary {
      padding: 12px 28px; background: var(--primary); color: #fff;
      border: none; border-radius: 8px; cursor: pointer; font-size: 1rem;
      transition: transform .2s, box-shadow .2s;
    }
    .btn-primary:hover { transform: translateY(-2px); box-shadow: 0 8px 30px rgba(108,99,255,.5); }

    /* Features */
    .features { padding: 100px 40px; }
    .features h2 { text-align: center; font-size: 2rem; margin-bottom: 60px; }
    .features h2 span { color: var(--primary); }
    .feature-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 24px; max-width: 1100px; margin: 0 auto; }
    .feature-card {
      background: var(--surface); border: 1px solid #1e1e3a;
      border-radius: 16px; padding: 32px;
      transition: transform .2s, border-color .2s;
    }
    .feature-card:hover { transform: translateY(-4px); border-color: var(--primary); }
    .feature-icon { font-size: 2rem; margin-bottom: 16px; }
    .feature-card h3 { font-size: 1.1rem; margin-bottom: 10px; }
    .feature-card p { color: var(--muted); font-size: .9rem; line-height: 1.6; }

    /* Footer */
    footer {
      text-align: center; padding: 40px;
      border-top: 1px solid #1e1e3a; color: var(--muted); font-size: .85rem;
    }
  </style>
</head>
<body>
  <nav>
    <div class="logo">NANO AI</div>
    <ul class="nav-links">
      <li><a href="#features">Features</a></li>
      <li><a href="#about">About</a></li>
      <li><a href="#contact">Contact</a></li>
    </ul>
    <button class="cta-btn">Get Started</button>
  </nav>

  <section class="hero">
    <div>
      <div class="hero-badge">✦ AI-Powered Coding</div>
      <h1>The AI that teaches<br><span>every language</span></h1>
      <p>Nano AI knows every programming language, framework, and concept.
         Learn by doing, get instant feedback, and build real projects.</p>
      <div class="hero-btns">
        <button class="btn-primary">Start Learning →</button>
        <button class="btn-outline">View Demo</button>
      </div>
    </div>
  </section>

  <section class="features" id="features">
    <h2>Everything you need to <span>master coding</span></h2>
    <div class="feature-grid">
      <div class="feature-card">
        <div class="feature-icon">🧠</div>
        <h3>AI-Powered Explanations</h3>
        <p>Ask anything about code. Get clear, concise explanations with real examples in any language.</p>
      </div>
      <div class="feature-card">
        <div class="feature-icon">⚡</div>
        <h3>Live Code Generation</h3>
        <p>Generate complete, production-quality scripts, UIs, 3D scenes, and APIs instantly.</p>
      </div>
      <div class="feature-card">
        <div class="feature-icon">🎯</div>
        <h3>Exercises & Quizzes</h3>
        <p>Practice with graded coding challenges from beginner to advanced. Earn XP and level up.</p>
      </div>
      <div class="feature-card">
        <div class="feature-icon">🌐</div>
        <h3>WebFetch</h3>
        <p>Nano AI browses the internet to fetch the latest documentation, tutorials, and answers.</p>
      </div>
      <div class="feature-card">
        <div class="feature-icon">📁</div>
        <h3>File Read & Write</h3>
        <p>Read your existing code, analyze it, and write improved versions directly to disk.</p>
      </div>
      <div class="feature-card">
        <div class="feature-icon">🔄</div>
        <h3>Persistent Memory</h3>
        <p>Nano AI remembers your progress, preferred language, and learned topics across sessions.</p>
      </div>
    </div>
  </section>

  <footer>
    <p>Built by Nano AI &mdash; the smartest coding tutor on Earth &mdash; 2024</p>
  </footer>
</body>
</html>"""
    return _wrap_output("Landing Page UI", "html", code)


def _gen_dashboard() -> str:
    code = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"><title>Nano AI Dashboard</title>
  <style>
    :root { --bg: #0d0d1a; --surface: #14142a; --border: #1e1e3a; --primary: #6c63ff; --accent: #ff6584; --green: #43e97b; --text: #e0e0f0; --muted: #666; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { background: var(--bg); color: var(--text); font-family: 'Segoe UI', system-ui, sans-serif; display: grid; grid-template-columns: 220px 1fr; min-height: 100vh; }
    /* Sidebar */
    .sidebar { background: var(--surface); border-right: 1px solid var(--border); padding: 24px 16px; display: flex; flex-direction: column; gap: 8px; }
    .sidebar-logo { font-size: 1.2rem; font-weight: 700; color: var(--primary); letter-spacing: 2px; padding: 0 8px 20px; }
    .nav-item { padding: 10px 12px; border-radius: 8px; cursor: pointer; font-size: .9rem; color: var(--muted); transition: all .15s; display: flex; gap: 10px; align-items: center; }
    .nav-item:hover, .nav-item.active { background: rgba(108,99,255,.15); color: var(--text); }
    .nav-item.active { color: var(--primary); }
    /* Main */
    .main { padding: 32px; overflow-y: auto; }
    .main-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 28px; }
    .main-header h1 { font-size: 1.4rem; }
    .badge { padding: 6px 14px; background: rgba(108,99,255,.15); color: var(--primary); border-radius: 20px; font-size: .8rem; }
    /* Stats */
    .stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 16px; margin-bottom: 28px; }
    .stat-card { background: var(--surface); border: 1px solid var(--border); border-radius: 12px; padding: 20px; }
    .stat-label { font-size: .8rem; color: var(--muted); margin-bottom: 8px; }
    .stat-value { font-size: 2rem; font-weight: 700; }
    .stat-value.purple { color: var(--primary); }
    .stat-value.pink   { color: var(--accent); }
    .stat-value.green  { color: var(--green); }
    .stat-delta { font-size: .8rem; color: var(--green); margin-top: 4px; }
    /* Chart area */
    .charts { display: grid; grid-template-columns: 2fr 1fr; gap: 16px; margin-bottom: 28px; }
    .chart-card { background: var(--surface); border: 1px solid var(--border); border-radius: 12px; padding: 20px; }
    .chart-card h3 { font-size: .95rem; margin-bottom: 16px; color: var(--muted); }
    .bar-chart { display: flex; align-items: flex-end; gap: 10px; height: 120px; }
    .bar { flex: 1; background: var(--primary); border-radius: 4px 4px 0 0; opacity: .7; transition: opacity .2s; cursor: pointer; position: relative; }
    .bar:hover { opacity: 1; }
    .bar::after { content: attr(data-val); position: absolute; top: -20px; left: 50%; transform: translateX(-50%); font-size: .7rem; color: var(--text); }
    .donut-wrap { display: flex; align-items: center; justify-content: center; height: 120px; }
    .donut { width: 100px; height: 100px; border-radius: 50%; background: conic-gradient(var(--primary) 0% 45%, var(--accent) 45% 70%, var(--green) 70% 100%); display: flex; align-items: center; justify-content: center; }
    .donut-inner { width: 60px; height: 60px; background: var(--surface); border-radius: 50%; }
    /* Table */
    table { width: 100%; border-collapse: collapse; }
    th, td { padding: 12px 16px; text-align: left; border-bottom: 1px solid var(--border); font-size: .9rem; }
    th { color: var(--muted); font-weight: 500; }
    .status { padding: 3px 10px; border-radius: 20px; font-size: .75rem; }
    .status.pass { background: rgba(67,233,123,.15); color: var(--green); }
    .status.fail { background: rgba(255,101,132,.15); color: var(--accent); }
    .status.warn { background: rgba(255,193,7,.15); color: #ffc107; }
  </style>
</head>
<body>
  <nav class="sidebar">
    <div class="sidebar-logo">NANO AI</div>
    <div class="nav-item active">📊 Dashboard</div>
    <div class="nav-item">📚 Learn</div>
    <div class="nav-item">🏋️ Exercises</div>
    <div class="nav-item">🧠 Quiz</div>
    <div class="nav-item">📁 Files</div>
    <div class="nav-item">🌐 WebFetch</div>
    <div class="nav-item">⚙️ Settings</div>
  </nav>
  <main class="main">
    <div class="main-header">
      <h1>Dashboard</h1>
      <span class="badge">Level 4 — Developer</span>
    </div>
    <div class="stats">
      <div class="stat-card"><div class="stat-label">Total XP</div><div class="stat-value purple">4,820</div><div class="stat-delta">↑ +120 today</div></div>
      <div class="stat-card"><div class="stat-label">Exercises Done</div><div class="stat-value pink">38</div><div class="stat-delta">↑ +3 today</div></div>
      <div class="stat-card"><div class="stat-label">Quiz Accuracy</div><div class="stat-value green">87%</div><div class="stat-delta">↑ +5% this week</div></div>
      <div class="stat-card"><div class="stat-label">Topics Covered</div><div class="stat-value purple">14</div><div class="stat-delta">All concepts ✓</div></div>
    </div>
    <div class="charts">
      <div class="chart-card">
        <h3>XP This Week</h3>
        <div class="bar-chart">
          <div class="bar" style="height:40%" data-val="180"></div>
          <div class="bar" style="height:65%" data-val="290"></div>
          <div class="bar" style="height:50%" data-val="220"></div>
          <div class="bar" style="height:80%" data-val="360"></div>
          <div class="bar" style="height:55%" data-val="245"></div>
          <div class="bar" style="height:90%" data-val="405"></div>
          <div class="bar" style="height:70%; background:#ff6584" data-val="120"></div>
        </div>
      </div>
      <div class="chart-card">
        <h3>Language Split</h3>
        <div class="donut-wrap"><div class="donut"><div class="donut-inner"></div></div></div>
        <div style="display:flex;gap:12px;justify-content:center;margin-top:12px;font-size:.75rem;color:var(--muted)">
          <span style="color:#6c63ff">● Python</span>
          <span style="color:#ff6584">● JS</span>
          <span style="color:#43e97b">● Lua</span>
        </div>
      </div>
    </div>
    <div class="chart-card">
      <h3>Recent Activity</h3><br>
      <table>
        <tr><th>Exercise</th><th>Language</th><th>Score</th><th>Status</th></tr>
        <tr><td>Binary Search</td><td>Python</td><td>100%</td><td><span class="status pass">Passed</span></td></tr>
        <tr><td>FizzBuzz</td><td>JavaScript</td><td>100%</td><td><span class="status pass">Passed</span></td></tr>
        <tr><td>Linked List</td><td>Python</td><td>60%</td><td><span class="status warn">Partial</span></td></tr>
        <tr><td>Merge Sort</td><td>Python</td><td>0%</td><td><span class="status fail">Skipped</span></td></tr>
      </table>
    </div>
  </main>
</body>
</html>"""
    return _wrap_output("Developer Dashboard UI", "html", code)


def _gen_cards() -> str:
    code = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"><title>Nano AI — Cards</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { min-height: 100vh; background: #0d0d1a; display: flex; flex-wrap: wrap; gap: 24px; align-items: center; justify-content: center; padding: 60px 40px; font-family: 'Segoe UI', system-ui, sans-serif; }

    .card {
      background: #14142a; border: 1px solid #1e1e3a; border-radius: 16px;
      width: 260px; overflow: hidden; transition: transform .25s, box-shadow .25s;
      cursor: pointer;
    }
    .card:hover { transform: translateY(-6px); box-shadow: 0 20px 50px rgba(108,99,255,.2); border-color: #6c63ff; }
    .card-img { width: 100%; height: 140px; object-fit: cover; display: flex; align-items: center; justify-content: center; font-size: 3rem; }
    .card-img.purple { background: linear-gradient(135deg, #3a1c71, #6c63ff); }
    .card-img.pink   { background: linear-gradient(135deg, #6b0f1a, #ff6584); }
    .card-img.green  { background: linear-gradient(135deg, #004d40, #43e97b); }
    .card-body { padding: 20px; }
    .card-tag { font-size: .7rem; color: #6c63ff; letter-spacing: 1px; text-transform: uppercase; margin-bottom: 8px; }
    .card-title { font-size: 1.1rem; margin-bottom: 8px; }
    .card-text { font-size: .85rem; color: #888; line-height: 1.6; }
    .card-footer { padding: 0 20px 20px; display: flex; justify-content: space-between; align-items: center; }
    .avatar { width: 28px; height: 28px; border-radius: 50%; background: linear-gradient(135deg,#6c63ff,#ff6584); display: flex; align-items: center; justify-content: center; font-size: .7rem; color: #fff; }
    .card-btn { padding: 6px 14px; background: rgba(108,99,255,.15); color: #6c63ff; border: 1px solid #6c63ff; border-radius: 20px; font-size: .75rem; cursor: pointer; transition: all .2s; }
    .card-btn:hover { background: #6c63ff; color: #fff; }
  </style>
</head>
<body>
  <div class="card">
    <div class="card-img purple">🧠</div>
    <div class="card-body">
      <div class="card-tag">AI &amp; Machine Learning</div>
      <div class="card-title">Neural Networks from Scratch</div>
      <div class="card-text">Build a neural net using only numpy. Understand backprop and gradient descent.</div>
    </div>
    <div class="card-footer"><div class="avatar">NA</div><button class="card-btn">Learn →</button></div>
  </div>
  <div class="card">
    <div class="card-img pink">⚡</div>
    <div class="card-body">
      <div class="card-tag">Web Development</div>
      <div class="card-title">Build a REST API with FastAPI</div>
      <div class="card-text">Create a full CRUD API with auth, database, and auto-generated docs in Python.</div>
    </div>
    <div class="card-footer"><div class="avatar">NA</div><button class="card-btn">Learn →</button></div>
  </div>
  <div class="card">
    <div class="card-img green">🎮</div>
    <div class="card-body">
      <div class="card-tag">Game Dev — Roblox</div>
      <div class="card-title">Scripting in Luau</div>
      <div class="card-text">Create NPCs, GUIs, weapons, and game loops using Roblox's Luau scripting engine.</div>
    </div>
    <div class="card-footer"><div class="avatar">NA</div><button class="card-btn">Learn →</button></div>
  </div>
</body>
</html>"""
    return _wrap_output("Card Components UI", "html", code)


def _gen_portfolio() -> str:
    code = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"><title>Portfolio — Nano AI</title>
  <style>
    :root { --primary:#6c63ff; --accent:#ff6584; --bg:#0d0d1a; --surface:#14142a; --text:#e0e0f0; --muted:#777; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    html { scroll-behavior: smooth; }
    body { background: var(--bg); color: var(--text); font-family: 'Segoe UI', system-ui, sans-serif; }
    section { padding: 80px 40px; max-width: 900px; margin: 0 auto; }
    /* Hero */
    .hero { min-height: 100vh; display: flex; align-items: center; }
    .hero-tag { color: var(--primary); font-size: .9rem; letter-spacing: 2px; margin-bottom: 12px; }
    .hero h1 { font-size: clamp(2.5rem,6vw,4.5rem); line-height: 1.1; margin-bottom: 16px; }
    .hero h1 em { font-style: normal; color: var(--primary); }
    .hero p { color: var(--muted); font-size: 1.1rem; max-width: 500px; line-height: 1.7; margin-bottom: 28px; }
    .hero-btns { display: flex; gap: 12px; flex-wrap: wrap; }
    .btn { padding: 11px 24px; border-radius: 8px; cursor: pointer; font-size: .95rem; transition: all .2s; }
    .btn-fill { background: var(--primary); color: #fff; border: none; }
    .btn-fill:hover { box-shadow: 0 8px 25px rgba(108,99,255,.5); transform: translateY(-2px); }
    .btn-ghost { background: transparent; color: var(--text); border: 1px solid #333; }
    .btn-ghost:hover { border-color: var(--primary); }
    /* About */
    .skills { display: flex; flex-wrap: wrap; gap: 10px; margin-top: 24px; }
    .skill { padding: 6px 14px; background: rgba(108,99,255,.1); border: 1px solid rgba(108,99,255,.3); border-radius: 20px; font-size: .85rem; color: var(--primary); }
    /* Projects */
    .projects { display: grid; grid-template-columns: repeat(auto-fit, minmax(260px,1fr)); gap: 20px; margin-top: 32px; }
    .proj { background: var(--surface); border: 1px solid #1e1e3a; border-radius: 12px; padding: 24px; transition: all .2s; }
    .proj:hover { border-color: var(--primary); transform: translateY(-4px); }
    .proj-top { display: flex; justify-content: space-between; margin-bottom: 14px; }
    .proj-icon { font-size: 1.8rem; }
    .proj-links a { color: var(--muted); font-size: .85rem; margin-left: 12px; text-decoration: none; }
    .proj-links a:hover { color: var(--text); }
    .proj h3 { margin-bottom: 8px; font-size: 1rem; }
    .proj p { color: var(--muted); font-size: .85rem; line-height: 1.6; margin-bottom: 14px; }
    .proj-tags { display: flex; gap: 6px; flex-wrap: wrap; }
    .proj-tag { font-size: .72rem; padding: 2px 8px; background: rgba(255,101,132,.1); color: var(--accent); border-radius: 4px; }
    /* Contact */
    .contact-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-top: 32px; }
    input, textarea { width: 100%; padding: 12px 16px; background: var(--surface); border: 1px solid #1e1e3a; border-radius: 8px; color: var(--text); font-size: .95rem; outline: none; transition: border-color .2s; }
    input:focus, textarea:focus { border-color: var(--primary); }
    textarea { grid-column: 1/-1; resize: vertical; min-height: 120px; }
    .contact-grid button { grid-column: 1/-1; }
  </style>
</head>
<body>
  <section class="hero">
    <div>
      <p class="hero-tag">// HELLO, WORLD</p>
      <h1>I build things<br>with <em>code</em></h1>
      <p>Full-stack developer · AI enthusiast · Open-source contributor. I turn ideas into fast, beautiful, production-ready software.</p>
      <div class="hero-btns">
        <button class="btn btn-fill">View Projects</button>
        <button class="btn btn-ghost">Download CV</button>
      </div>
    </div>
  </section>
  <section>
    <h2>About Me</h2>
    <p style="color:var(--muted);line-height:1.8;margin-top:16px">
      I'm a software engineer who loves building things from scratch. I work across the full stack — from React frontends and Node backends to Python data pipelines and Lua game scripts.
    </p>
    <div class="skills">
      <span class="skill">Python</span><span class="skill">JavaScript</span><span class="skill">TypeScript</span>
      <span class="skill">React</span><span class="skill">Node.js</span><span class="skill">Lua / Roblox</span>
      <span class="skill">Rust</span><span class="skill">SQL</span><span class="skill">Docker</span>
      <span class="skill">Three.js</span><span class="skill">Machine Learning</span>
    </div>
  </section>
  <section>
    <h2>Projects</h2>
    <div class="projects">
      <div class="proj">
        <div class="proj-top"><span class="proj-icon">🧠</span><div class="proj-links"><a href="#">GitHub</a><a href="#">Demo</a></div></div>
        <h3>Nano AI Tutor</h3>
        <p>AI coding tutor that teaches every language, generates code, and browses the web. Fully offline.</p>
        <div class="proj-tags"><span class="proj-tag">Python</span><span class="proj-tag">AI</span><span class="proj-tag">CLI</span></div>
      </div>
      <div class="proj">
        <div class="proj-top"><span class="proj-icon">🎮</span><div class="proj-links"><a href="#">GitHub</a></div></div>
        <h3>Roblox Game Framework</h3>
        <p>Modular Luau framework for Roblox games. Includes NPC AI, inventory, and networking.</p>
        <div class="proj-tags"><span class="proj-tag">Lua</span><span class="proj-tag">Roblox</span><span class="proj-tag">Game Dev</span></div>
      </div>
      <div class="proj">
        <div class="proj-top"><span class="proj-icon">⚡</span><div class="proj-links"><a href="#">GitHub</a><a href="#">Live</a></div></div>
        <h3>Real-time Dashboard</h3>
        <p>WebSocket-powered analytics dashboard with live charts, dark mode, and mobile support.</p>
        <div class="proj-tags"><span class="proj-tag">React</span><span class="proj-tag">Node</span><span class="proj-tag">WebSocket</span></div>
      </div>
    </div>
  </section>
  <section>
    <h2>Contact</h2>
    <form>
      <div class="contact-grid">
        <input type="text" placeholder="Name">
        <input type="email" placeholder="Email">
        <textarea placeholder="Your message..."></textarea>
        <button class="btn btn-fill" type="submit">Send Message →</button>
      </div>
    </form>
  </section>
</body>
</html>"""
    return _wrap_output("Portfolio Website", "html", code)


# ─── Roblox / Lua ─────────────────────────────────────────────────────────────

def _gen_roblox(hint: str) -> str:
    if "gui" in hint or "ui" in hint:
        code = _roblox_gui()
        return _wrap_output("Roblox GUI Script", "lua", code)
    if "npc" in hint or "enemy" in hint:
        code = _roblox_npc()
        return _wrap_output("Roblox NPC AI Script", "lua", code)
    code = _roblox_game_loop()
    return _wrap_output("Roblox Game Loop Script", "lua", code)


def _roblox_gui() -> str:
    return """-- Nano AI — Roblox GUI Script (LocalScript)
local Players      = game:GetService("Players")
local TweenService = game:GetService("TweenService")
local UserInputService = game:GetService("UserInputService")

local player  = Players.LocalPlayer
local gui     = player:WaitForChild("PlayerGui")

-- Create ScreenGui
local screenGui = Instance.new("ScreenGui")
screenGui.Name         = "NanoHUD"
screenGui.ResetOnSpawn = false
screenGui.Parent       = gui

-- Main frame
local frame = Instance.new("Frame")
frame.Size            = UDim2.new(0, 280, 0, 200)
frame.Position        = UDim2.new(0.5, -140, 0.5, -100)
frame.BackgroundColor3 = Color3.fromRGB(13, 13, 26)
frame.BorderSizePixel  = 0
frame.Parent           = screenGui

-- Rounded corners
Instance.new("UICorner", frame).CornerRadius = UDim.new(0, 12)

-- Stroke / border
local stroke = Instance.new("UIStroke", frame)
stroke.Color     = Color3.fromRGB(108, 99, 255)
stroke.Thickness = 2

-- Title label
local title = Instance.new("TextLabel", frame)
title.Size      = UDim2.new(1, 0, 0, 40)
title.Position  = UDim2.new(0, 0, 0, 0)
title.Text      = "⚡ NANO AI HUD"
title.TextColor3 = Color3.fromRGB(108, 99, 255)
title.Font      = Enum.Font.GothamBold
title.TextSize  = 16
title.BackgroundTransparency = 1

-- Stats
local function makeLabel(parent, text, posY)
    local lbl = Instance.new("TextLabel", parent)
    lbl.Size      = UDim2.new(1, -20, 0, 30)
    lbl.Position  = UDim2.new(0, 10, 0, posY)
    lbl.Text      = text
    lbl.TextColor3 = Color3.fromRGB(200, 200, 220)
    lbl.Font      = Enum.Font.Gotham
    lbl.TextSize  = 14
    lbl.TextXAlignment = Enum.TextXAlignment.Left
    lbl.BackgroundTransparency = 1
    return lbl
end

local hpLabel    = makeLabel(frame, "❤️  HP: 100 / 100", 45)
local xpLabel    = makeLabel(frame, "⭐ XP: 0", 75)
local levelLabel = makeLabel(frame, "🏆 Level: 1", 105)

-- Close button
local closeBtn = Instance.new("TextButton", frame)
closeBtn.Size      = UDim2.new(0, 24, 0, 24)
closeBtn.Position  = UDim2.new(1, -28, 0, 8)
closeBtn.Text      = "✕"
closeBtn.TextColor3 = Color3.fromRGB(255, 100, 100)
closeBtn.Font      = Enum.Font.GothamBold
closeBtn.TextSize  = 14
closeBtn.BackgroundTransparency = 1
closeBtn.BorderSizePixel = 0

-- Tween open animation
local tweenInfo = TweenInfo.new(0.3, Enum.EasingStyle.Back, Enum.EasingDirection.Out)
frame.Size = UDim2.new(0, 0, 0, 0)
TweenService:Create(frame, tweenInfo, { Size = UDim2.new(0, 280, 0, 200) }):Play()

-- Toggle visibility on close
closeBtn.MouseButton1Click:Connect(function()
    local tween = TweenService:Create(frame, TweenInfo.new(0.2), { Size = UDim2.new(0, 0, 0, 0) })
    tween:Play()
    tween.Completed:Wait()
    frame.Visible = false
end)

-- Drag the frame
local dragging, dragStart, startPos = false, nil, nil
frame.InputBegan:Connect(function(input)
    if input.UserInputType == Enum.UserInputType.MouseButton1 then
        dragging  = true
        dragStart = input.Position
        startPos  = frame.Position
    end
end)
frame.InputEnded:Connect(function(input)
    if input.UserInputType == Enum.UserInputType.MouseButton1 then
        dragging = false
    end
end)
UserInputService.InputChanged:Connect(function(input)
    if dragging and input.UserInputType == Enum.UserInputType.MouseMovement then
        local delta = input.Position - dragStart
        frame.Position = UDim2.new(
            startPos.X.Scale, startPos.X.Offset + delta.X,
            startPos.Y.Scale, startPos.Y.Offset + delta.Y
        )
    end
end)

-- Update stats from character
local function updateStats()
    local char = player.Character
    if not char then return end
    local hum = char:FindFirstChildOfClass("Humanoid")
    if hum then
        hpLabel.Text = string.format("❤️  HP: %d / %d", math.floor(hum.Health), math.floor(hum.MaxHealth))
    end
end
game:GetService("RunService").Heartbeat:Connect(updateStats)
print("[NanoAI] GUI loaded successfully!")
"""


def _roblox_npc() -> str:
    return """-- Nano AI — Roblox NPC AI (ServerScript)
local Players      = game:GetService("Players")
local RunService   = game:GetService("RunService")
local PathfindingService = game:GetService("PathfindingService")

local NPC          = script.Parent
local humanoid     = NPC:WaitForChild("Humanoid")
local rootPart     = NPC:WaitForChild("HumanoidRootPart")

-- Config
local DETECT_RANGE  = 50    -- studs to spot a player
local ATTACK_RANGE  = 5     -- studs to deal damage
local ATTACK_DAMAGE = 15
local ATTACK_COOLDOWN = 1.5
local WALK_SPEED    = 14
local CHASE_SPEED   = 18
local WANDER_RADIUS = 20

humanoid.WalkSpeed = WALK_SPEED

local spawnPos    = rootPart.Position
local lastAttack  = 0
local target      = nil

-- ── Utilities ──────────────────────────────────────────────────
local function getClosestPlayer()
    local closest, dist = nil, DETECT_RANGE
    for _, p in ipairs(Players:GetPlayers()) do
        local char = p.Character
        if char and char:FindFirstChild("HumanoidRootPart") then
            local d = (char.HumanoidRootPart.Position - rootPart.Position).Magnitude
            if d < dist then
                closest, dist = char, d
            end
        end
    end
    return closest
end

local function moveTo(position)
    local path = PathfindingService:CreatePath({
        AgentRadius = 2, AgentHeight = 5,
        AgentCanJump = true, AgentCanClimb = false,
    })
    local ok, err = pcall(function() path:ComputeAsync(rootPart.Position, position) end)
    if not ok or path.Status ~= Enum.PathStatus.Success then
        humanoid:MoveTo(position)
        return
    end
    for _, wp in ipairs(path:GetWaypoints()) do
        if wp.Action == Enum.PathWaypointAction.Jump then
            humanoid.Jump = true
        end
        humanoid:MoveTo(wp.Position)
        local reached = humanoid.MoveToFinished:Wait(1)
        if not reached then break end
        if target and (rootPart.Position - target.HumanoidRootPart.Position).Magnitude < ATTACK_RANGE then break end
    end
end

local function wander()
    local angle  = math.random() * 2 * math.pi
    local offset = Vector3.new(math.cos(angle) * WANDER_RADIUS, 0, math.sin(angle) * WANDER_RADIUS)
    moveTo(spawnPos + offset)
end

local function attack()
    if not target then return end
    local dist = (rootPart.Position - target.HumanoidRootPart.Position).Magnitude
    if dist > ATTACK_RANGE then return end
    local now = tick()
    if now - lastAttack < ATTACK_COOLDOWN then return end
    lastAttack = now
    local hum = target:FindFirstChildOfClass("Humanoid")
    if hum and hum.Health > 0 then
        hum:TakeDamage(ATTACK_DAMAGE)
    end
end

-- ── Main loop ──────────────────────────────────────────────────
while true do
    if humanoid.Health <= 0 then break end

    target = getClosestPlayer()

    if target and target:FindFirstChild("HumanoidRootPart") then
        local dist = (rootPart.Position - target.HumanoidRootPart.Position).Magnitude
        humanoid.WalkSpeed = CHASE_SPEED
        if dist <= ATTACK_RANGE then
            humanoid:MoveTo(rootPart.Position)  -- stand still
            attack()
        else
            moveTo(target.HumanoidRootPart.Position)
        end
    else
        humanoid.WalkSpeed = WALK_SPEED
        wander()
        task.wait(math.random(2, 5))
    end

    task.wait(0.1)
end
"""


def _roblox_game_loop() -> str:
    return """-- Nano AI — Roblox Game Loop (ServerScript)
local Players      = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local ServerStorage     = game:GetService("ServerStorage")

-- ── Events ────────────────────────────────────────────────────
local events = Instance.new("Folder", ReplicatedStorage)
events.Name  = "Events"

local roundStarted = Instance.new("RemoteEvent", events)
roundStarted.Name  = "RoundStarted"

local roundEnded   = Instance.new("RemoteEvent", events)
roundEnded.Name    = "RoundEnded"

local updateScore  = Instance.new("RemoteEvent", events)
updateScore.Name   = "UpdateScore"

-- ── Game config ────────────────────────────────────────────────
local CONFIG = {
    LOBBY_TIME   = 15,
    ROUND_TIME   = 120,
    MIN_PLAYERS  = 2,
    MAP_FOLDER   = ServerStorage:FindFirstChild("Maps"),
}

-- ── State ─────────────────────────────────────────────────────
local scores     = {}
local roundActive = false

-- ── Utilities ─────────────────────────────────────────────────
local function teleportToLobby(player)
    local char = player.Character
    if char and char:FindFirstChild("HumanoidRootPart") then
        char.HumanoidRootPart.CFrame = CFrame.new(0, 5, 0)
    end
end

local function killAll()
    for _, player in ipairs(Players:GetPlayers()) do
        local char = player.Character
        if char then
            local hum = char:FindFirstChildOfClass("Humanoid")
            if hum then hum.Health = 0 end
        end
    end
end

local function notifyAll(message, color)
    color = color or Color3.fromRGB(255, 255, 255)
    for _, player in ipairs(Players:GetPlayers()) do
        local gui = player:FindFirstChild("PlayerGui")
        if gui then
            local sg = Instance.new("ScreenGui", gui)
            sg.ResetOnSpawn = false
            local lbl = Instance.new("TextLabel", sg)
            lbl.Size      = UDim2.new(1, 0, 0, 60)
            lbl.Position  = UDim2.new(0, 0, 0.1, 0)
            lbl.Text      = message
            lbl.TextColor3 = color
            lbl.Font      = Enum.Font.GothamBold
            lbl.TextSize  = 28
            lbl.BackgroundTransparency = 1
            game:GetService("Debris"):AddItem(sg, 4)
        end
    end
end

-- ── Player events ─────────────────────────────────────────────
Players.PlayerAdded:Connect(function(player)
    scores[player.UserId] = 0
    player.CharacterAdded:Connect(function(char)
        if not roundActive then
            task.wait(1)
            teleportToLobby(player)
        end
        local hum = char:WaitForChild("Humanoid")
        hum.Died:Connect(function()
            local tag = hum:FindFirstChild("creator")
            if tag and tag.Value and tag.Value ~= player then
                local killer = tag.Value
                scores[killer.UserId] = (scores[killer.UserId] or 0) + 1
                updateScore:FireAll(killer, scores[killer.UserId])
                notifyAll(killer.Name .. " eliminated " .. player.Name, Color3.fromRGB(255, 100, 100))
            end
        end)
    end)
    print("[NanoAI] " .. player.Name .. " joined. Players: " .. #Players:GetPlayers())
end)

Players.PlayerRemoving:Connect(function(player)
    scores[player.UserId] = nil
end)

-- ── Main game loop ────────────────────────────────────────────
while true do
    -- Lobby countdown
    notifyAll("⏳ Waiting for players... (" .. #Players:GetPlayers() .. "/" .. CONFIG.MIN_PLAYERS .. ")")
    repeat task.wait(1) until #Players:GetPlayers() >= CONFIG.MIN_PLAYERS

    for i = CONFIG.LOBBY_TIME, 1, -1 do
        notifyAll("🚀 Round starting in " .. i .. "s!", Color3.fromRGB(108, 99, 255))
        task.wait(1)
    end

    -- Reset scores
    scores = {}
    for _, p in ipairs(Players:GetPlayers()) do
        scores[p.UserId] = 0
    end

    -- Start round
    roundActive = true
    roundStarted:FireAll()
    notifyAll("⚔️  ROUND STARTED! Fight!", Color3.fromRGB(255, 200, 0))

    -- Respawn players in map
    for _, player in ipairs(Players:GetPlayers()) do
        player:LoadCharacter()
        task.wait(0.1)
    end

    -- Round timer
    local timeLeft = CONFIG.ROUND_TIME
    while timeLeft > 0 and roundActive do
        task.wait(1)
        timeLeft -= 1
        if timeLeft % 30 == 0 and timeLeft > 0 then
            notifyAll("⏱  " .. timeLeft .. "s remaining!")
        end
        -- Check win condition (all but one eliminated)
        local alive = {}
        for _, p in ipairs(Players:GetPlayers()) do
            local char = p.Character
            local hum  = char and char:FindFirstChildOfClass("Humanoid")
            if hum and hum.Health > 0 then
                table.insert(alive, p)
            end
        end
        if #alive <= 1 then
            roundActive = false
            if alive[1] then
                notifyAll("🏆 " .. alive[1].Name .. " WINS!", Color3.fromRGB(255, 215, 0))
            end
        end
    end

    -- End round
    roundActive = false
    roundEnded:FireAll()
    notifyAll("🔁 Round over! Returning to lobby...", Color3.fromRGB(108, 99, 255))
    killAll()
    task.wait(3)
    for _, player in ipairs(Players:GetPlayers()) do
        task.wait(0.2)
        player:LoadCharacter()
        task.wait(0.5)
        teleportToLobby(player)
    end
    task.wait(3)
end
"""


# ─── Python scripts ────────────────────────────────────────────────────────────

def _gen_python(hint: str) -> str:
    if "flask" in hint or "web" in hint:
        code = _python_flask()
        return _wrap_output("Flask Web Server", "python", code)
    if "scraper" in hint or "scrape" in hint:
        code = _python_scraper()
        return _wrap_output("Web Scraper", "python", code)
    code = _python_data_pipeline()
    return _wrap_output("Python Data Pipeline", "python", code)


def _python_flask() -> str:
    return '''"""
Nano AI — Flask REST API with auth, CRUD, and rate limiting
Run: pip install flask flask-jwt-extended && python app.py
"""
from flask import Flask, request, jsonify, g
from functools import wraps
import hashlib, secrets, time, json, os
from datetime import datetime, timedelta

app = Flask(__name__)
app.config["SECRET_KEY"] = secrets.token_hex(32)

# ── In-memory store (swap for a real DB in production) ──────────
USERS = {}       # {username: {password_hash, created}}
TOKENS = {}      # {token: {username, expires}}
ITEMS  = {}      # {id: {title, body, owner, created}}
RATE   = {}      # {ip: [timestamps]}

# ── Helpers ──────────────────────────────────────────────────────
def hash_pw(pw: str) -> str:
    return hashlib.sha256(pw.encode()).hexdigest()

def new_token(username: str) -> str:
    token   = secrets.token_hex(32)
    expires = datetime.utcnow() + timedelta(hours=24)
    TOKENS[token] = {"username": username, "expires": expires}
    return token

def rate_limit(max_per_minute=60):
    """Decorator: limit requests per IP."""
    def decorator(f):
        @wraps(f)
        def wrapper(*args, **kwargs):
            ip  = request.remote_addr
            now = time.time()
            RATE.setdefault(ip, [])
            RATE[ip] = [t for t in RATE[ip] if now - t < 60]
            if len(RATE[ip]) >= max_per_minute:
                return jsonify(error="Rate limit exceeded"), 429
            RATE[ip].append(now)
            return f(*args, **kwargs)
        return wrapper
    return decorator

def auth_required(f):
    """Decorator: require valid bearer token."""
    @wraps(f)
    def wrapper(*args, **kwargs):
        token = request.headers.get("Authorization", "").removeprefix("Bearer ").strip()
        info  = TOKENS.get(token)
        if not info or datetime.utcnow() > info["expires"]:
            return jsonify(error="Unauthorized"), 401
        g.username = info["username"]
        return f(*args, **kwargs)
    return wrapper

# ── Auth routes ──────────────────────────────────────────────────
@app.post("/auth/register")
@rate_limit(10)
def register():
    data = request.json or {}
    u, p = data.get("username","").strip(), data.get("password","")
    if not u or not p or len(p) < 6:
        return jsonify(error="username and password (min 6 chars) required"), 400
    if u in USERS:
        return jsonify(error="Username already exists"), 409
    USERS[u] = {"password_hash": hash_pw(p), "created": datetime.utcnow().isoformat()}
    return jsonify(message="Registered successfully"), 201

@app.post("/auth/login")
@rate_limit(10)
def login():
    data = request.json or {}
    u, p = data.get("username",""), data.get("password","")
    user = USERS.get(u)
    if not user or user["password_hash"] != hash_pw(p):
        return jsonify(error="Invalid credentials"), 401
    token = new_token(u)
    return jsonify(token=token, expires_in="24h")

@app.post("/auth/logout")
@auth_required
def logout():
    token = request.headers.get("Authorization","").removeprefix("Bearer ").strip()
    TOKENS.pop(token, None)
    return jsonify(message="Logged out")

# ── CRUD routes ──────────────────────────────────────────────────
@app.get("/items")
@auth_required
@rate_limit()
def list_items():
    user_items = [{"id":k,**v} for k,v in ITEMS.items() if v["owner"]==g.username]
    return jsonify(items=user_items, count=len(user_items))

@app.post("/items")
@auth_required
def create_item():
    data  = request.json or {}
    title = data.get("title","").strip()
    body  = data.get("body","")
    if not title:
        return jsonify(error="title is required"), 400
    item_id = secrets.token_hex(8)
    ITEMS[item_id] = {"title":title,"body":body,"owner":g.username,"created":datetime.utcnow().isoformat()}
    return jsonify(id=item_id, **ITEMS[item_id]), 201

@app.get("/items/<item_id>")
@auth_required
def get_item(item_id):
    item = ITEMS.get(item_id)
    if not item or item["owner"] != g.username:
        return jsonify(error="Not found"), 404
    return jsonify(id=item_id, **item)

@app.put("/items/<item_id>")
@auth_required
def update_item(item_id):
    item = ITEMS.get(item_id)
    if not item or item["owner"] != g.username:
        return jsonify(error="Not found"), 404
    data = request.json or {}
    if "title" in data: item["title"] = data["title"]
    if "body"  in data: item["body"]  = data["body"]
    return jsonify(id=item_id, **item)

@app.delete("/items/<item_id>")
@auth_required
def delete_item(item_id):
    item = ITEMS.get(item_id)
    if not item or item["owner"] != g.username:
        return jsonify(error="Not found"), 404
    del ITEMS[item_id]
    return jsonify(message="Deleted")

# ── Health ────────────────────────────────────────────────────────
@app.get("/health")
def health():
    return jsonify(status="ok", users=len(USERS), items=len(ITEMS))

if __name__ == "__main__":
    print("🚀 Nano AI Flask API running at http://localhost:5000")
    app.run(debug=True, port=5000)
'''


def _python_scraper() -> str:
    return '''"""
Nano AI — Web Scraper (urllib only, no external deps)
Scrapes a page, extracts headings and links, saves to JSON.
"""
import urllib.request, urllib.parse, html, re, json, time, sys
from datetime import datetime

HEADERS = {
    "User-Agent": "Mozilla/5.0 (compatible; NanoAI-Scraper/1.0)"
}

def fetch(url: str) -> str:
    req = urllib.request.Request(url, headers=HEADERS)
    with urllib.request.urlopen(req, timeout=10) as resp:
        return resp.read().decode(resp.headers.get_content_charset("utf-8"), errors="replace")

def clean(text: str) -> str:
    text = re.sub(r"<[^>]+>", " ", text)
    text = html.unescape(text)
    return re.sub(r"\\s+", " ", text).strip()

def scrape(url: str) -> dict:
    print(f"Fetching: {url}")
    raw = fetch(url)

    title_m = re.search(r"<title[^>]*>(.*?)</title>", raw, re.I|re.S)
    title   = clean(title_m.group(1)) if title_m else "No title"

    headings = re.findall(r"<h[1-3][^>]*>(.*?)</h[1-3]>", raw, re.I|re.S)
    headings = [clean(h) for h in headings][:20]

    links = re.findall(r'href=["\\'](https?://[^"\\'\\s>]+)', raw, re.I)
    links = list(dict.fromkeys(links))[:30]  # unique, preserve order

    paragraphs = re.findall(r"<p[^>]*>(.*?)</p>", raw, re.I|re.S)
    paragraphs = [clean(p) for p in paragraphs if len(clean(p)) > 40][:10]

    return {
        "url":        url,
        "title":      title,
        "scraped_at": datetime.utcnow().isoformat(),
        "headings":   headings,
        "links":      links,
        "paragraphs": paragraphs,
    }

def crawl(start_url: str, max_pages: int = 5, delay: float = 1.0) -> list:
    visited = set()
    queue   = [start_url]
    results = []
    base    = "{u.scheme}://{u.netloc}".format(u=urllib.parse.urlparse(start_url))

    while queue and len(results) < max_pages:
        url = queue.pop(0)
        if url in visited: continue
        visited.add(url)
        try:
            data = scrape(url)
            results.append(data)
            # Enqueue same-domain links
            for link in data["links"]:
                if link.startswith(base) and link not in visited:
                    queue.append(link)
            time.sleep(delay)
        except Exception as e:
            print(f"  Error scraping {url}: {e}")

    return results

if __name__ == "__main__":
    target  = sys.argv[1] if len(sys.argv) > 1 else "https://example.com"
    pages   = int(sys.argv[2]) if len(sys.argv) > 2 else 3
    results = crawl(target, max_pages=pages)

    out_file = "scraped_data.json"
    with open(out_file, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2, ensure_ascii=False)

    print(f"\\nScraped {len(results)} pages → {out_file}")
    for r in results:
        print(f"  • {r[\'title\'][:60]} ({len(r[\'links\'])} links)")
'''


def _python_data_pipeline() -> str:
    return '''"""
Nano AI — Data Processing Pipeline (stdlib only)
Reads CSV, cleans data, analyses, and outputs report.
"""
import csv, json, statistics, re
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path

# ── Sample data generator ─────────────────────────────────────
SAMPLE_CSV = """name,age,city,score,date
Alice,28,New York,92,2024-01-15
Bob,35,London,78,2024-01-16
Carol,22,Tokyo,95,2024-01-16
Dave,,Paris,65,2024-01-17
Eve,29,New York,88,2024-01-18
Frank,41,London,,2024-01-18
Grace,19,Tokyo,91,2024-01-19
Henry,55,Paris,72,2024-01-20
Iris,33,New York,84,2024-01-20
Jack,27,London,79,2024-01-21
"""

# ── Loader ────────────────────────────────────────────────────
def load_csv(path=None, raw=None) -> list[dict]:
    if raw:
        import io
        reader = csv.DictReader(io.StringIO(raw))
    else:
        reader = csv.DictReader(open(path, encoding="utf-8"))
    return list(reader)

# ── Cleaner ───────────────────────────────────────────────────
def clean(records: list[dict]) -> list[dict]:
    cleaned, skipped = [], 0
    for row in records:
        try:
            age   = int(row["age"]) if row.get("age") else None
            score = float(row["score"]) if row.get("score") else None
            cleaned.append({
                "name":  row["name"].strip().title(),
                "age":   age,
                "city":  row["city"].strip(),
                "score": score,
                "date":  datetime.strptime(row["date"], "%Y-%m-%d"),
            })
        except Exception:
            skipped += 1
    print(f"  Loaded {len(cleaned)} rows, skipped {skipped} invalid")
    return cleaned

# ── Analyser ──────────────────────────────────────────────────
def analyse(records: list[dict]) -> dict:
    scores  = [r["score"] for r in records if r["score"] is not None]
    ages    = [r["age"]   for r in records if r["age"]   is not None]
    cities  = Counter(r["city"] for r in records)
    by_city = defaultdict(list)
    for r in records:
        if r["score"]: by_city[r["city"]].append(r["score"])

    city_avg = {c: round(statistics.mean(sc), 1) for c, sc in by_city.items()}
    top      = max(records, key=lambda r: r["score"] or 0)
    low      = min(records, key=lambda r: r["score"] or 999)

    return {
        "total_records": len(records),
        "scores": {
            "mean":   round(statistics.mean(scores), 2),
            "median": statistics.median(scores),
            "stdev":  round(statistics.stdev(scores), 2),
            "min":    min(scores), "max": max(scores),
        },
        "ages": {
            "mean":   round(statistics.mean(ages), 1),
            "min":    min(ages), "max": max(ages),
        },
        "city_distribution": dict(cities),
        "avg_score_by_city": city_avg,
        "top_scorer": {"name": top["name"], "score": top["score"]},
        "lowest_scorer": {"name": low["name"], "score": low["score"]},
    }

# ── Reporter ──────────────────────────────────────────────────
def report(analysis: dict) -> str:
    a = analysis
    lines = [
        "=" * 55,
        "  NANO AI — DATA PIPELINE REPORT",
        f"  Generated: {datetime.now().strftime(\'%Y-%m-%d %H:%M:%S\')}",
        "=" * 55,
        f"  Total records:  {a[\'total_records\']}",
        "",
        "  SCORE STATISTICS:",
        f"    Mean:    {a[\'scores\'][\'mean\']}",
        f"    Median:  {a[\'scores\'][\'median\']}",
        f"    Std Dev: {a[\'scores\'][\'stdev\']}",
        f"    Range:   {a[\'scores\'][\'min\']} – {a[\'scores\'][\'max\']}",
        "",
        "  AGE STATS:",
        f"    Mean: {a[\'ages\'][\'mean\']}  Range: {a[\'ages\'][\'min\']}–{a[\'ages\'][\'max\']}",
        "",
        "  CITY DISTRIBUTION:",
    ]
    for city, count in sorted(a["city_distribution"].items(), key=lambda x:-x[1]):
        avg  = a["avg_score_by_city"].get(city, "N/A")
        bar  = "█" * count
        lines.append(f"    {city:<12} {bar} ({count})  avg score: {avg}")
    lines += [
        "",
        f"  🏆 Top scorer:    {a[\'top_scorer\'][\'name\']} ({a[\'top_scorer\'][\'score\']})",
        f"  📉 Lowest scorer: {a[\'lowest_scorer\'][\'name\']} ({a[\'lowest_scorer\'][\'score\']})",
        "=" * 55,
    ]
    return "\\n".join(lines)

# ── Main ──────────────────────────────────────────────────────
if __name__ == "__main__":
    print("\\n[Nano AI] Data Pipeline\\n")
    raw     = load_csv(raw=SAMPLE_CSV)
    cleaned = clean(raw)
    result  = analyse(cleaned)
    print(report(result))

    Path("analysis.json").write_text(json.dumps(result, indent=2, default=str))
    print("\\n  Full analysis saved to analysis.json")
'''


# ─── JavaScript / Node ────────────────────────────────────────────────────────

def _gen_javascript(hint: str) -> str:
    if "react" in hint:
        code = _js_react_app()
        return _wrap_output("React App (vanilla)", "html", code)
    code = _js_node_api()
    return _wrap_output("Node.js Express API", "javascript", code)


def _js_react_app() -> str:
    code = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"><title>Nano AI — React App</title>
  <script src="https://unpkg.com/react@18/umd/react.development.js"></script>
  <script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { background: #0d0d1a; color: #e0e0f0; font-family: 'Segoe UI', system-ui, sans-serif; min-height: 100vh; padding: 40px; }
    .container { max-width: 600px; margin: 0 auto; }
    h1 { color: #6c63ff; font-size: 1.6rem; margin-bottom: 24px; text-align: center; }
    .input-row { display: flex; gap: 10px; margin-bottom: 24px; }
    input { flex: 1; padding: 12px 16px; background: #14142a; border: 1px solid #1e1e3a; border-radius: 8px; color: #e0e0f0; font-size: 1rem; outline: none; }
    input:focus { border-color: #6c63ff; }
    button { padding: 12px 20px; background: #6c63ff; color: #fff; border: none; border-radius: 8px; cursor: pointer; font-size: 1rem; transition: opacity .2s; }
    button:hover { opacity: .85; }
    .todo-item { display: flex; align-items: center; gap: 12px; padding: 14px 16px; background: #14142a; border: 1px solid #1e1e3a; border-radius: 10px; margin-bottom: 10px; transition: border-color .2s; }
    .todo-item:hover { border-color: #6c63ff; }
    .todo-item.done span { text-decoration: line-through; color: #555; }
    .todo-check { width: 20px; height: 20px; border: 2px solid #6c63ff; border-radius: 50%; cursor: pointer; display: flex; align-items: center; justify-content: center; flex-shrink: 0; transition: background .2s; }
    .todo-check.checked { background: #6c63ff; }
    .todo-item span { flex: 1; }
    .del-btn { background: rgba(255,101,132,.15); color: #ff6584; border: 1px solid rgba(255,101,132,.3); padding: 4px 10px; border-radius: 6px; cursor: pointer; font-size: .8rem; }
    .del-btn:hover { background: rgba(255,101,132,.3); }
    .stats { text-align: center; color: #555; font-size: .85rem; margin-top: 16px; }
    .filter-row { display: flex; gap: 8px; margin-bottom: 16px; justify-content: center; }
    .filter-btn { padding: 6px 14px; background: transparent; border: 1px solid #1e1e3a; border-radius: 20px; color: #888; cursor: pointer; font-size: .8rem; transition: all .2s; }
    .filter-btn.active { border-color: #6c63ff; color: #6c63ff; background: rgba(108,99,255,.1); }
    .empty { text-align: center; color: #333; padding: 40px; }
  </style>
</head>
<body>
<div id="root"></div>
<script type="text/babel">
const { useState, useMemo } = React;

function TodoApp() {
  const [todos,  setTodos]  = useState([
    { id: 1, text: 'Learn React hooks',  done: true  },
    { id: 2, text: 'Build a cool app',   done: false },
    { id: 3, text: 'Ship to production', done: false },
  ]);
  const [input,  setInput]  = useState('');
  const [filter, setFilter] = useState('all');

  const addTodo = () => {
    const text = input.trim();
    if (!text) return;
    setTodos(prev => [...prev, { id: Date.now(), text, done: false }]);
    setInput('');
  };

  const toggle = id => setTodos(prev => prev.map(t => t.id === id ? { ...t, done: !t.done } : t));
  const remove = id => setTodos(prev => prev.filter(t => t.id !== id));

  const visible = useMemo(() => {
    if (filter === 'active')    return todos.filter(t => !t.done);
    if (filter === 'completed') return todos.filter(t =>  t.done);
    return todos;
  }, [todos, filter]);

  const done  = todos.filter(t =>  t.done).length;
  const total = todos.length;

  return (
    <div className="container">
      <h1>⚡ Nano AI Todo</h1>
      <div className="input-row">
        <input
          value={input}
          onChange={e => setInput(e.target.value)}
          onKeyDown={e => e.key === 'Enter' && addTodo()}
          placeholder="Add a new task..."
        />
        <button onClick={addTodo}>Add</button>
      </div>
      <div className="filter-row">
        {['all','active','completed'].map(f => (
          <button key={f} className={`filter-btn ${filter===f?'active':''}`} onClick={() => setFilter(f)}>
            {f.charAt(0).toUpperCase()+f.slice(1)}
          </button>
        ))}
      </div>
      {visible.length === 0
        ? <div className="empty">No tasks here 🎉</div>
        : visible.map(t => (
            <div key={t.id} className={`todo-item ${t.done?'done':''}`}>
              <div className={`todo-check ${t.done?'checked':''}`} onClick={() => toggle(t.id)}>
                {t.done && '✓'}
              </div>
              <span>{t.text}</span>
              <button className="del-btn" onClick={() => remove(t.id)}>Delete</button>
            </div>
          ))
      }
      <div className="stats">{done} of {total} tasks completed</div>
    </div>
  );
}

ReactDOM.createRoot(document.getElementById('root')).render(<TodoApp />);
</script>
</body>
</html>"""
    return _wrap_output("React Todo App (CDN)", "html", code)


def _js_node_api() -> str:
    return """// Nano AI — Node.js Express REST API
// Run: npm install express && node server.js

const express = require('express');
const crypto  = require('crypto');

const app  = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());

// ── In-memory store ──────────────────────────────────────────
const users = new Map();  // Map<id, User>
const items = new Map();  // Map<id, Item>

// ── Helpers ──────────────────────────────────────────────────
const uid   = () => crypto.randomBytes(8).toString('hex');
const hash  = pw => crypto.createHash('sha256').update(pw).digest('hex');
const ok    = (res, data, status = 200) => res.status(status).json(data);
const err   = (res, msg, status = 400) => res.status(status).json({ error: msg });

// ── Middleware: request logger ────────────────────────────────
app.use((req, _res, next) => {
  console.log(`${new Date().toISOString()} ${req.method} ${req.path}`);
  next();
});

// ── Users ────────────────────────────────────────────────────
app.post('/users', (req, res) => {
  const { name, email, password } = req.body || {};
  if (!name || !email || !password)
    return err(res, 'name, email, and password are required');
  if ([...users.values()].find(u => u.email === email))
    return err(res, 'Email already registered', 409);

  const id   = uid();
  const user = { id, name, email, passwordHash: hash(password), createdAt: new Date() };
  users.set(id, user);
  const { passwordHash, ...safeUser } = user;
  return ok(res, safeUser, 201);
});

app.get('/users', (_req, res) => {
  const list = [...users.values()].map(({ passwordHash, ...u }) => u);
  return ok(res, { users: list, count: list.length });
});

app.get('/users/:id', (req, res) => {
  const user = users.get(req.params.id);
  if (!user) return err(res, 'User not found', 404);
  const { passwordHash, ...safeUser } = user;
  return ok(res, safeUser);
});

app.put('/users/:id', (req, res) => {
  const user = users.get(req.params.id);
  if (!user) return err(res, 'User not found', 404);
  const { name, email } = req.body || {};
  if (name)  user.name  = name;
  if (email) user.email = email;
  user.updatedAt = new Date();
  const { passwordHash, ...safeUser } = user;
  return ok(res, safeUser);
});

app.delete('/users/:id', (req, res) => {
  if (!users.delete(req.params.id))
    return err(res, 'User not found', 404);
  return ok(res, { message: 'Deleted' });
});

// ── Items (owned by users) ────────────────────────────────────
app.post('/users/:userId/items', (req, res) => {
  if (!users.has(req.params.userId))
    return err(res, 'User not found', 404);
  const { title, body = '' } = req.body || {};
  if (!title) return err(res, 'title is required');
  const id   = uid();
  const item = { id, userId: req.params.userId, title, body, createdAt: new Date() };
  items.set(id, item);
  return ok(res, item, 201);
});

app.get('/users/:userId/items', (req, res) => {
  const list = [...items.values()].filter(i => i.userId === req.params.userId);
  return ok(res, { items: list, count: list.length });
});

app.delete('/items/:id', (req, res) => {
  if (!items.delete(req.params.id)) return err(res, 'Not found', 404);
  return ok(res, { message: 'Deleted' });
});

// ── Health ────────────────────────────────────────────────────
app.get('/health', (_req, res) =>
  ok(res, { status: 'ok', users: users.size, items: items.size, uptime: process.uptime() })
);

// ── 404 ───────────────────────────────────────────────────────
app.use((req, res) => err(res, `Route ${req.method} ${req.path} not found`, 404));

// ── Start ─────────────────────────────────────────────────────
app.listen(PORT, () =>
  console.log(`🚀 Nano AI Node API → http://localhost:${PORT}`)
);"""


# ─── REST API (generic) ────────────────────────────────────────────────────────

def _gen_rest_api(hint: str) -> str:
    if "node" in hint or "javascript" in hint or "express" in hint:
        return _wrap_output("Node.js Express API", "javascript", _js_node_api())
    return _wrap_output("Flask REST API", "python", _python_flask())


# ─── SQL ──────────────────────────────────────────────────────────────────────

def _gen_sql(hint: str) -> str:
    code = """-- Nano AI — Complete SQL Schema + Sample Queries
-- Compatible with SQLite, PostgreSQL, MySQL

-- ── Schema ────────────────────────────────────────────────────
CREATE TABLE users (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    username   TEXT    NOT NULL UNIQUE,
    email      TEXT    NOT NULL UNIQUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    is_active  BOOLEAN DEFAULT 1
);

CREATE TABLE categories (
    id   INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE posts (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
    title       TEXT    NOT NULL,
    body        TEXT    NOT NULL DEFAULT '',
    views       INTEGER NOT NULL DEFAULT 0,
    created_at  DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE comments (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    post_id    INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    body       TEXT    NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tags (
    id   INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE post_tags (
    post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    tag_id  INTEGER NOT NULL REFERENCES tags(id)  ON DELETE CASCADE,
    PRIMARY KEY (post_id, tag_id)
);

-- ── Indexes ───────────────────────────────────────────────────
CREATE INDEX idx_posts_user     ON posts(user_id);
CREATE INDEX idx_posts_category ON posts(category_id);
CREATE INDEX idx_posts_created  ON posts(created_at);
CREATE INDEX idx_comments_post  ON comments(post_id);

-- ── Seed data ─────────────────────────────────────────────────
INSERT INTO users (username, email) VALUES
  ('alice', 'alice@example.com'),
  ('bob',   'bob@example.com'),
  ('carol', 'carol@example.com');

INSERT INTO categories (name) VALUES ('Tech'), ('Science'), ('Gaming'), ('Art');

INSERT INTO posts (user_id, category_id, title, body, views) VALUES
  (1, 1, 'Getting started with Python', 'Python is a great first language...', 420),
  (2, 1, 'Why Rust is taking over',     'Rust eliminates memory bugs...', 810),
  (1, 3, 'Roblox scripting in 2024',    'Luau is fast and type-safe...', 330),
  (3, 2, 'Quantum computing explained', 'Qubits can be both 0 and 1...', 610);

INSERT INTO comments (post_id, user_id, body) VALUES
  (1, 2, 'Great intro!'), (1, 3, 'Saved me hours'), (2, 1, 'Love Rust!');

INSERT INTO tags (name) VALUES ('python'),('rust'),('lua'),('tutorial'),('beginner');
INSERT INTO post_tags VALUES (1,1),(1,4),(1,5),(2,2),(3,3),(3,4);

-- ── Useful queries ────────────────────────────────────────────

-- Posts with author name, category, comment count
SELECT
    p.id,
    p.title,
    u.username  AS author,
    c.name      AS category,
    COUNT(cm.id) AS comment_count,
    p.views
FROM posts p
JOIN users      u  ON u.id  = p.user_id
LEFT JOIN categories c  ON c.id  = p.category_id
LEFT JOIN comments   cm ON cm.post_id = p.id
GROUP BY p.id
ORDER BY p.views DESC;

-- Top authors by post count
SELECT u.username, COUNT(p.id) AS posts
FROM users u
LEFT JOIN posts p ON p.user_id = u.id
GROUP BY u.id
ORDER BY posts DESC;

-- Posts with all their tags (comma-separated)
SELECT p.title, GROUP_CONCAT(t.name, ', ') AS tags
FROM posts p
JOIN post_tags pt ON pt.post_id = p.id
JOIN tags     t   ON t.id       = pt.tag_id
GROUP BY p.id;

-- Full-text search simulation
SELECT * FROM posts
WHERE title LIKE '%python%' OR body LIKE '%python%';

-- Pagination (page 2, 10 per page)
SELECT * FROM posts ORDER BY created_at DESC LIMIT 10 OFFSET 10;

-- Transaction example
BEGIN;
UPDATE posts SET views = views + 1 WHERE id = 1;
INSERT INTO comments (post_id, user_id, body) VALUES (1, 3, 'New comment!');
COMMIT;
"""
    return _wrap_output("Complete SQL Schema + Queries", "sql", code)


# ─── General fallback ─────────────────────────────────────────────────────────

def _gen_general(request: str) -> str:
    r = request.lower()
    # Detect language
    lang_map = {
        "python": ("python", "def hello():\n    print('Hello, World!')\n\nhello()"),
        "java":   ("java",   'public class Main {\n    public static void main(String[] args) {\n        System.out.println("Hello, World!");\n    }\n}'),
        "rust":   ("rust",   'fn main() {\n    println!("Hello, World!");\n}'),
        "go":     ("go",     'package main\nimport "fmt"\nfunc main() { fmt.Println("Hello, World!") }'),
        "c++":    ("cpp",    '#include<iostream>\nint main(){std::cout<<"Hello, World!"<<std::endl;return 0;}'),
        "lua":    ("lua",    'print("Hello, World!")'),
    }
    for kw, (lang, snippet) in lang_map.items():
        if kw in r:
            return _wrap_output(f"Hello World in {lang.title()}", lang, snippet)

    return (
        "\n  🛠️  CODE GENERATOR\n"
        "  ─────────────────────────────────────────\n\n"
        "  I can generate complete, production-quality code.\n"
        "  Try one of these:\n\n"
        "    generate a 3D rotating cube\n"
        "    generate CSS animations\n"
        "    generate a landing page\n"
        "    generate a React todo app\n"
        "    generate a Flask API\n"
        "    generate a Node.js Express server\n"
        "    generate a Python web scraper\n"
        "    generate a SQL schema\n"
        "    generate a Roblox game loop\n"
        "    generate a Roblox GUI script\n"
        "    generate a Roblox NPC AI\n"
        "    generate a portfolio website\n"
        "    generate a dashboard UI\n"
    )


# ─── Output wrapper ───────────────────────────────────────────────────────────

def _wrap_output(title: str, lang: str, code: str) -> str:
    lines = code.strip().split("\n")
    header = (
        f"\n  ⚡ NANO AI GENERATED — {title.upper()}\n"
        f"  {'─'*65}\n"
        f"  Language: {lang}   Lines: {len(lines)}\n"
        f"  {'─'*65}\n\n"
    )
    body = "\n".join("  " + l for l in lines)
    footer = (
        f"\n\n  {'─'*65}\n"
        f"  Copy the code above. Save as a .{_ext(lang)} file and run it!\n"
        f"  Type 'generate [something else]' for more code.\n"
    )
    return header + body + footer


def _ext(lang: str) -> str:
    return {
        "python": "py", "javascript": "js", "typescript": "ts",
        "lua": "lua", "java": "java", "rust": "rs", "go": "go",
        "html": "html", "css": "css", "sql": "sql", "cpp": "cpp",
    }.get(lang.lower(), lang[:3])
