/* build-modules.js
 * Regenerate modules.js by embedding the luau-vm Lua sources. Run whenever
 * ../../luau-vm/src changes:  node obfuscator-site/vm/build-modules.js
 *
 * Sources are stripped to ASCII (comments only) so they round-trip cleanly
 * through Fengari's JS<->Lua UTF-8 conversion in the browser.
 */
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..', '..', 'luau-vm', 'src');
const OUT = path.join(__dirname, 'modules.js');

// modules needed to COMPILE in the browser
const COMPILE = ['opcodes', 'bitops', 'lexer', 'parser', 'scope', 'optimizer',
  'compiler', 'serializer', 'seal', 'vm', 'api', 'harden', 'webbundle'];
// modules bundled into the emitted output (the runtime that executes bytecode)
const RUNTIME = ['opcodes', 'bitops', 'serializer', 'seal', 'vm'];

const toAscii = (s) => s.replace(/[^\x00-\x7F]/g, ''); // drop non-ASCII (comments only)
const read = (m) => toAscii(fs.readFileSync(path.join(SRC, m + '.lua'), 'utf8'));

const mods = Object.fromEntries(COMPILE.map((m) => [m, read(m)]));
const rt = Object.fromEntries(RUNTIME.map((m) => [m, read(m)]));

const out = '/* Auto-generated by build-modules.js from luau-vm/src (ASCII-sanitized for Fengari). */\n'
  + 'window.LUAU_VM_MODULES=' + JSON.stringify(mods) + ';\n'
  + 'window.LUAU_VM_RUNTIME=' + JSON.stringify(rt) + ';\n';

if ((out.match(/[^\x00-\x7F]/g) || []).length !== 0) throw new Error('non-ASCII leaked into modules.js');
fs.writeFileSync(OUT, out, 'utf8');
console.log('wrote', OUT, '(' + out.length + ' bytes; compile=' + COMPILE.length + ' runtime=' + RUNTIME.length + ')');
