# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: renderer.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'renderer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erenderer.proto\x12\x08render3d\"\x80\x01\n\rRenderRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x18\n\x10source_asset_key\x18\x02 \x01(\t\x12\x15\n\rtarget_format\x18\x03 \x01(\t\x12\x16\n\x0esimplify_ratio\x18\x04 \x01(\x02\x12\x16\n\x0e\x64raco_compress\x18\x05 \x01(\x08\"0\n\x0eRenderResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x1f\n\rStatusRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"Q\n\x0cStatusUpdate\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x10\n\x08progress\x18\x03 \x01(\x02\x12\x0f\n\x07message\x18\x04 \x01(\t2\x95\x01\n\rRenderService\x12\x41\n\x0cSubmitRender\x12\x17.render3d.RenderRequest\x1a\x18.render3d.RenderResponse\x12\x41\n\x0cStreamStatus\x12\x17.render3d.StatusRequest\x1a\x16.render3d.StatusUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'renderer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RENDERREQUEST']._serialized_start=29
  _globals['_RENDERREQUEST']._serialized_end=157
  _globals['_RENDERRESPONSE']._serialized_start=159
  _globals['_RENDERRESPONSE']._serialized_end=207
  _globals['_STATUSREQUEST']._serialized_start=209
  _globals['_STATUSREQUEST']._serialized_end=240
  _globals['_STATUSUPDATE']._serialized_start=242
  _globals['_STATUSUPDATE']._serialized_end=323
  _globals['_RENDERSERVICE']._serialized_start=326
  _globals['_RENDERSERVICE']._serialized_end=475
# @@protoc_insertion_point(module_scope)
