# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc_gen import renderer_pb2 as renderer__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in renderer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RenderServiceStub(object):
    """Internal service-to-service contract: the API layer calls this to hand a
    render job to a dedicated GPU worker pool without going through HTTP/Celery.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitRender = channel.unary_unary(
                '/render3d.RenderService/SubmitRender',
                request_serializer=renderer__pb2.RenderRequest.SerializeToString,
                response_deserializer=renderer__pb2.RenderResponse.FromString,
                _registered_method=True)
        self.StreamStatus = channel.unary_stream(
                '/render3d.RenderService/StreamStatus',
                request_serializer=renderer__pb2.StatusRequest.SerializeToString,
                response_deserializer=renderer__pb2.StatusUpdate.FromString,
                _registered_method=True)


class RenderServiceServicer(object):
    """Internal service-to-service contract: the API layer calls this to hand a
    render job to a dedicated GPU worker pool without going through HTTP/Celery.
    """

    def SubmitRender(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RenderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitRender': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitRender,
                    request_deserializer=renderer__pb2.RenderRequest.FromString,
                    response_serializer=renderer__pb2.RenderResponse.SerializeToString,
            ),
            'StreamStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamStatus,
                    request_deserializer=renderer__pb2.StatusRequest.FromString,
                    response_serializer=renderer__pb2.StatusUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'render3d.RenderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('render3d.RenderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RenderService(object):
    """Internal service-to-service contract: the API layer calls this to hand a
    render job to a dedicated GPU worker pool without going through HTTP/Celery.
    """

    @staticmethod
    def SubmitRender(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/render3d.RenderService/SubmitRender',
            renderer__pb2.RenderRequest.SerializeToString,
            renderer__pb2.RenderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/render3d.RenderService/StreamStatus',
            renderer__pb2.StatusRequest.SerializeToString,
            renderer__pb2.StatusUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
